### ISSUE TITLE
Add a fedmsg message id header to emails

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn#101]
See #100.  There are `X-Fedmsg-...` headers, but it would be nice to know _exactly_ which fedmsg triggered that email.  The original messages have a unique id which can be used to look them up in datagrepper.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
