### ISSUE TITLE
Koji link is incorrect for secondary arch builds

### ISSUE THREAD

**Issue by siddhesh** [fedora-infra/fmn#102]
I just got this notification:

12:37 <fedora-notifs> sharkcz's glibc-2.21.90-20.fc23 completed http://koji.fedoraproject.org/koji/buildinfo?buildID=346105

which is wrong.  The build did happen, but in a different koji instance.  The correct link should have been:

http://s390.koji.fedoraproject.org/koji/buildinfo?buildID=346105

that is, it should have pointed to the secondary arch koji instance.

**Comment by siddhesh** [comment]
Same issue with emails as well.  It looks like it queries the main koji instance for the build or task ID and then formulates an email, ending up with the subject line saying "glibc-2.21.90-20.fc23" but the content being for the python-cement build in the main koji instance instead of the glibc build in the s390 koji instance.

**Comment by ralphbean** [comment]
Thanks for the report!  The s390 koji instance was rebuilt and added to ansible recently but it got a copy of the fedmsg plugin from the primary instance.  Fixed here:  https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=eb5ab70642066574225bb0d6dcc18ecd8ef9169f
