### ISSUE TITLE
need way to get commits to scm-commits mailing list

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fmn#1024]
The old fmn was used to watch all commits on src.fedoraproject.org and send them to the scm-commits@lists.fedoraproject.org list. 
Since I took down the old FMN, there's no more emails there. ;( 

This list was super high volume, but it was a way to have commits for all packages transparently go out and allow auditing from 3rd parties, etc. It would be super nice if we could make this work again. 

I'm out next week, but hopefully @abompard could look into it? 

We could perhaps move this to a infra ticket also...

**Comment by abompard** [comment]
I think it would be a nice exercise for someone who wants to learn writing a fedora-messaging consumer. Or maybe even a toddler.
Unrelated to FMN though, because FMN is really for user-configured things.
Let's move it to an infra ticket and mark it "good first issue" (or the equivalent there)

**Comment by nirik** [comment]
Sure, except... it's down right now. The longer it takes to setup again... the longer the gap in posts and time with less visibility/auditing for commits. ;(

**Comment by abompard** [comment]
Oh, right. Let's move it to an infra ticket anyway then, so it can be prioritized correctly. I can take a shot at it.

https://pagure.io/fedora-infrastructure/issue/11641
