### ISSUE TITLE
Missing "an update can be pushed to stable" Bodhi rule

### ISSUE THREAD

**Issue by ppisar** [fedora-infra/fmn#104]
I cannot find a Bodhi rule to match event when an update can be requested to push into stable. Please add this rule the FMN intarface.

See http://permalink.gmane.org/gmane.linux.redhat.fedora.devel/212372 for more details.

**Comment by pypingou** [comment]
Is there a fedmsg message sent when an update can be pushed to stable? If not I doubt FMN can do anything about it :)

**Comment by ralphbean** [comment]
Nope.  See fedora-infra/bodhi#298.

We can/should add a fedmsg event there if we can.

**Comment by pypingou** [comment]
Ah, I knew there was a ticket about it, I just failed to find it again :(

**Comment by voxik** [comment]
ping, any news about this? https://github.com/fedora-infra/bodhi/issues/298 is closed for some while but still no notification ...

**Comment by voxik** [comment]
Ha, actually I received notification yesterday:

https://bodhi.fedoraproject.org/updates/ruby-2.2.3-46.fc22#comment-369042

So this might actually work.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
