### ISSUE TITLE
Possible to enable notifications to zero email addresses

### ISSUE THREAD

**Issue by mavit** [fedora-infra/fmn#105]
Email notification is enabled, so why don't I get any notifications?

![notifications-screenshot](https://cloud.githubusercontent.com/assets/120296/10710231/61fa7936-7a47-11e5-9494-6191cad9686b.png)

It turns out that this is because notifications are enabled to the empty set of email addresses.  My FAS-registered email address isn't used, and I need to register an email address with Notifications by clicking <kbd>Update</kbd>.  I don't think this is obvious from the UI in the screenshot.

Related issue: I heard that I was supposed to be able to set filtering rules, but I couldn't find that feature, either.  Turned out that was also behind the <kbd>Update</kbd> button.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
