### ISSUE TITLE
no Matrix notifications for multiple hours - messages lost instead of being re-sent after service was resumed

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/fmn#1064]
see $SUBJECT

At about 6 PM (UTC+1) on Jan. 13, 2024, I noticed that I didn't get any messages from the "Fedora Notifications" Matrix bot since 9 AM (UTC+1), even though there should have been between a few dozen and a few hundred messages due to my own activity. I asked about this in the `#admin:fedoraproject.org` room on Matrix:

- Fabio Valentini: is there a problem with fedora notifications? I haven't received any Matrix messages in the last ~8 hours, but there should have been hundreds of messages 
- nirik: will look
- nirik: is it sending to you now? it claims it is...
  `[2024-01-13 17:20:55,395] [INFO fmn.sender.matrix] Sending message to [@decathorpe:fedora.im](https://matrix.to/#/@decathorpe:fedora.im): [Koji] Build COMPLETE: decathorpe's rust-gstreamer-video-0.21.2-1.fc39 https://koji.fedoraproject.org/koji/buildinfo?buildID=2345100`
- Fabio Valentini: nirik: yes, it is now
  looks like it dropped at least a few dozen messages though :)
- nirik: I am not fully sure what happened... I think possibly it was refreshing it's cache (mappings of packages to packagers) and that failed somehow so it stopped being able to route? not sure.
- Fabio Valentini:  weird, but that would explain it
- nirik: but even more oddly, I didn't directly do anything to it... I just fixed our ipa cluster (there was a server update and needed ipa-server-update run). Possibly that was somehow causing it to not get those usernames? but that seems odd, because other things were working just fine.
- Fabio Valentini: this isn't the first time it happened ... if it happens again, I'll file a ticket so it can be investigated properly 
- nirik: yeah. Actually, can you file a upstream fmn ticket on it? perhaps someone can look monday and still see what happened?
  (or I can in a bit)
- Fabio Valentini: that would be at https://github.com/fedora-infra/fmn/ ?
- nirik: yep

**Comment by abompard** [comment]
I think I found why. The cache refresh makes a few API calls, and one of them failed on your username:
```
2024-01-13 09:22:03|refresh-cache-early-28418901-gt6nn|Request failed: Server error '500 Internal Server Error' for url 'https://src.fedoraproject.org/api/0/projects?short=false&fork=false&username=decathorpe&per_page=20&page=18'
```
I think that in this situation, FMN will skip the request and consider that it returned nothing. So the cache will believe that you don't have any packages, and not notify you.

FMN should probably:
- keep its previous value if the cache refresh failed
- retry on 500 erros, if that does not take too long

**Comment by abompard** [comment]
I did the retry/backoff change in #1066, but I think it won't be simple to keep the previous cached value on failure as proposed above, because of how the components call each other. Let's see if this fix is sufficient first.
