### ISSUE TITLE
Support a generic strucuted data query.

### ISSUE THREAD

**Issue by tomprince** [fedora-infra/fmn#107]
Something like https://stedolan.github.io/jq/ or http://jmespath.org/

**Comment by ralphbean** [comment]
For whoever takes this on, it would only require that a new rule be added to [this file in fmn.rules](https://github.com/fedora-infra/fmn.rules/blob/develop/fmn/rules/generic.py).

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
