### ISSUE TITLE
Receiving notifications from a rule which should not be sending them

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/fmn#108]
I have the following rule configured:
https://apps.fedoraproject.org/notifications/tibbs.id.fedoraproject.org/email/30432
It's simple: select all packages for which I'm in the commit ACL, but don't show me builds starting or tagger events.

However, I keep receiving notifications via that rule for packages where I only have watchcommits set.  or example, I'll stick one at the end of this message.

threebean indicates that the problem may be somewhere in https://github.com/fedora-infra/fmn.rules/blob/develop/fmn/rules/generic.py#L100-L122

```
Return-Path: <notifications@fedoraproject.org>
Received: from util1.math.uh.edu ([unix socket])
         by util1.math.uh.edu (Cyrus v2.3.16-Fedora-RPM-2.3.16-2.el5) with LMTPA;
         Wed, 18 Nov 2015 17:00:59 -0600
X-Sieve: CMU Sieve 2.3
Received: from mx2.math.uh.edu ([129.7.128.33])
        by util1.math.uh.edu with esmtp (Exim 4.63)
        (envelope-from <notifications@fedoraproject.org>)
        id 1ZzBil-00052z-UY
        for tibbs@math.uh.edu; Wed, 18 Nov 2015 17:00:59 -0600
Received: from bastion01.fedoraproject.org ([209.132.181.2] helo=bastion.fedoraproject.org)
        by mx2.math.uh.edu with esmtp (Exim 4.85)
        (envelope-from <notifications@fedoraproject.org>)
        id 1ZzBil-00062L-Aw
        for tibbs@math.uh.edu; Wed, 18 Nov 2015 17:00:59 -0600
Received: by bastion01.phx2.fedoraproject.org (Postfix)
        id 13F7E604E828; Wed, 18 Nov 2015 23:00:59 +0000 (UTC)
Delivered-To: tibbs@fedoraproject.org
Received: from notifs-backend01.phx2.fedoraproject.org (notifs-backend01.phx2.fedoraproject.org [10.5.126.168])
        by bastion01.phx2.fedoraproject.org (Postfix) with ESMTP id 0C84E604E826
        for <tibbs@fedoraproject.org>; Wed, 18 Nov 2015 23:00:59 +0000 (UTC)
To: tibbs@fedoraproject.org
From: notifications@fedoraproject.org
X-Fedmsg-Topic: org.fedoraproject.prod.mdapi.repo.update
X-Fedmsg-Category: mdapi
X-Fedmsg-Package: kernel
X-Fedmsg-Package: kernel-tools-libs-devel
X-Fedmsg-Package: kernel-devel
X-Fedmsg-Package: kernel-debug-modules-extra
X-Fedmsg-Package: kernel-tools
X-Fedmsg-Package: perf
X-Fedmsg-Package: kernel-headers
X-Fedmsg-Package: kernel-debug-core
X-Fedmsg-Package: kernel-debug-modules
X-Fedmsg-Package: kernel-core
X-Fedmsg-Package: kernel-debug
X-Fedmsg-Package: kernel-tools-libs
X-Fedmsg-Package: kernel-modules
X-Fedmsg-Package: kernel-debug-devel
X-Fedmsg-Package: python-perf
X-Fedmsg-Package: kernel-modules-extra
Subject: mdapi meta-data update: changelog: +64/-64
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
Message-Id: <20151118230059.0C84E604E826@bastion01.phx2.fedoraproject.org>
Date: Wed, 18 Nov 2015 23:00:59 +0000 (UTC)
X-Spam-Score: -8.5 (--------)

mdapi meta-data update: changelog: +64/-64
        https://download.fedoraproject.org/pub/rawhide/latest/x86_64/repodata/08d79daa8de9b99e70564672d07b11f98369b30ccb2f71cb02d89746f56dbfae\
-other.sqlite.bz2

--
You received this message due to your preference settings at
https://apps.fedoraproject.org/notifications/tibbs.id.fedoraproject.org/email/30432
```

**Comment by jasontibbitts** [comment]
Unfortunately I'm still having exactly the same problem.  Sadly it means that I due to the torrent of notifications I end up missing things for packages I actually own, so I've ended up having to do my own filtering locally.  Just having watchcommits on the kernel, firefox or texlive means that I get every ABRT report and whatnot through the rule that's supposed to match packages I actually maintain.

**Comment by pypingou** [comment]
ftr, I've tried to replicate the code locally:

````
>>> import requests
>>> req = requests.get('https://admin.fedoraproject.org/pkgdb/api/packager/package/tibbs')
>>> req.status_code
200
>>> data = req.json()
>>> data.keys()
[u'output', u'co-maintained', u'watch', u'point of contact']
>>> flags = only_commit = ['point of contact', 'co-maintained']
>>> packages_of_interest = sum([data[flag] for flag in flags], [])
>>> packages_of_interest = set([p['name'] for p in packages_of_interest])
>>> sorted(packages_of_interest)
[u'amanda', u'apcupsd', u'cyrus-imapd', u'denyhosts', u'epel-rpm-macros', u'fedora-obsolete-packages', u'fedora-rpm-macros', u'kcm_wacomtablet', u'nazghul', u'perl-Encode-IMAPUTF7', u'perl-PHP-Serialization', u'perl-Parallel-ForkManager',
 u'perl-Sys-Mmap', u'php-channel-horde', u'python-rpm-macros', u'pyzor', u'rpmlint', u'swaks', u'tig', u'xu4', u'zsh']
````

So the logic looks good here.

**Comment by jasontibbitts** [comment]
Just to make sure it wasn't some stale data or anything, I went ahead and simply deleted all of my rules and started afresh.  I have two rules: one for "watchcommits flag" and one for "commit acl".  For the kernel package I get, say, ABRT and bugzilla notifications through the first rule (as indicated in the URL at the bottom of the email).

If I then add some negated rules to the "watchcommits" rule to eliminate abrt and bugzilla update notifications, I begin to get them through the second rule.

Just to be absolutely sure, I've now gone into pkgdb and stopped watching kernel and firefox just to make sure the email stops.

The only other thing I can think of is that I'm a provenpackager and also in the cvsadmin group (and also a pkgdb admin(.  I know those all interact with pkgdb ACLs in specific ways which I suppose could be confusing.  But I agree that pingou's data above does appear to be correct.

For the record, the relevant rules are now:

https://apps.fedoraproject.org/notifications/tibbs.id.fedoraproject.org/email/49475/ (watchcommits with various negations)

https://apps.fedoraproject.org/notifications/tibbs.id.fedoraproject.org/email/49495/ (commit acl, with no negations)

I also have https://apps.fedoraproject.org/notifications/tibbs.id.fedoraproject.org/email/49476/ which is just things mentioning me which aren't related to my packages.

At this point I think the only real way out is to add a filter to the commit acl rule which explicitly filters out messages for packages I'm only watching.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
