### ISSUE TITLE
there seems to be no rule to filter out fedora-infra ansible git repo events

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#110]
I have the following filter defined:
https://apps.fedoraproject.org/notifications/kparal.id.fedoraproject.org/irc/20807/
I hope you can see it with your superpowers. It basically watches for any mention of "taskotron" in a message.

I'm getting the following messages on IRC:

```
<fedora-notifs> infragit.receive -- mkrizek pushed a commit to the fedora-infra ansible repo (master):  "Try this" 2 minutes ago https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?h=master&id=453e8620557d8d0eb74469e38081812958c09c43
<fedora-notifs> infragit.receive -- mkrizek pushed a commit to the fedora-infra ansible repo (master):  "taskotron-client configs: Revert to the previous state" 2 minutes ago https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?h=master&id=95e0872f4fd30a1e87aa007b0eab13441c41d5e7
```

Due to #109 I don't exactly know which filter causes these messages, but I consider it quite obvious it's the one mentioned. I have added the following rule:

```
 An ansible action from Fedora-Infra
```

and negated it, and I stopped receiving some messages, like:

```
<fedora-notifs> ansible.playbook.complete -- root's playbooks/run_fasClient.yml playbook run completed 7 minutes ago http://infrastructure.fedoraproject.org/cgit/ansible.git/tree/playbooks/run_fasClient.yml
```

however I still keep getting those `infragit.receive` messages.

It seems to me that those `infragit.receive` message should either be excluded by that `An ansible action from Fedora-Infra` rule, or there should be another rule for "git commits to fedora-infra repos". But there are no such rules available, there are only rules for dist-git and github, which is not related.

**Comment by ralphbean** [comment]
@kparal fedora-infra/fmn.rules#64 should add the new rule.

**Comment by kparal** [comment]
Thanks, looking forward to having it deployed :-)
