### ISSUE TITLE
No notifications from copr

### ISSUE THREAD

**Issue by knurd** [fedora-infra/fmn#1107]
Ever since the switch to the new FMN I didn't get any notifications from copr; part of the problem was supposed to be fixed by https://github.com/fedora-copr/copr/pull/3099; those changes since last week are now in production. But I still do not get any notifications. But it seems they are generated on the copr side of things: https://apps.fedoraproject.org/datagrepper/v2/id?id=e0e225c0-899a-4174-9a5f-84307ea2e666&is_raw=true&size=extra-large This is from a test build.

The "messages send in the last 7 days" counter on the FMN front page did not change before/after the test build, so I assume it's not a local problem. FWIW, this is my FMN configuration: ![Screenshot FMN thl](https://github.com/fedora-infra/fmn/assets/2239565/49fd05ba-e153-4de6-abdf-07dd347a9cbc).

**Comment by abompard** [comment]
OK I have investigated this, and I think the reason is that the version of the copr schema is too old in production. Not sure we can update it while the freeze is in place though. I have tested with the more recent schema and the message you pointed should generate notification(s).

**Comment by knurd** [comment]
> investigated this

Many thx!

> Not sure we can update it while the freeze is in place though

It's broken for a while already afaics, so no need to hurry, a few weeks more won't make much of a difference now. 😆

Thx again!

**Comment by nirik** [comment]
If the change needs to happen in FMN, it's not frozen. ;)

**Comment by abompard** [comment]
It's been updated in prod, do you get notifications from Copr now  @knurd ?

**Comment by knurd** [comment]
> do you get notifications from Copr now @knurd ?

Yeah, I do. Great, many many  thx!

Now I just need to get the copr folks to look into https://github.com/fedora-copr/copr/issues/3176, as notifications triggered by a namespaces username are the ones I care about. 🥴  Anyway, not your problem, thx again!
