### ISSUE TITLE
rjones proposed subject lines

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn#111]
rjones [proposed this on the devel list](https://lists.fedoraproject.org/archives/list/infrastructure%40lists.fedoraproject.org/thread/4SPFSPTUR5VY5QDFAOF72B3G3JGHPJVE/).  We could easily modify the FMN emails to match the pattern described there.

Making similar changes to Bodhi is a pain.  Half the point of FMN was that we wouldn't have to modify email code in other systems when we want to do something like this.  We can either:
- make the change also in bodhi
- or figure out whatever else needs to happen to turn off emails from bodhi all together.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
