### ISSUE TITLE
f24 build is notified in f23 ticket

### ISSUE THREAD

**Issue by voxik** [fedora-infra/fmn#112]
Recently, I received this notification:

```
vondruch's real build of rubygem-will_paginate-3.1.0-1.fc24 for RHBZ#1239978 completed
    https://bugzilla.redhat.com/show_bug.cgi?id=1239978
```

But if you'll check the ticket it is F23 bug, so the build should not be referenced there IMO.

Actually, this is very likely not the right tracker, please redirect me into the correct one

**Comment by pypingou** [comment]
The-new-hotness is most likely the correct tracker, as for the bug, I'm not sure if the-new-hotness checks the release set in the ticket .

**Comment by ralphbean** [comment]
FWIW, it **was** a rawhide bug.

/me hides!

**Comment by voxik** [comment]
Thx, moving the ticket ....
