### ISSUE TITLE
Copr messages are excitingly useless

### ISSUE THREAD

**Issue by penguinpee** [fedora-infra/fmn#1138]
I'm reporting this here as a starting point since FMN is sending those messages. It may well prove to be an issue elsewhere (e.g. Copr). Feel free to transfer.

Now that Copr FMN messages finally work I find them excitingly useless. An example:

```
Subject: [Copr] org.fedoraproject.prod.copr.build.end

Copr Message in project "gui1ty/updates": build 7377504: chroot "fedora-rawhide-x86_64" ended as "succeeded".
```

That's all. It doesn't tell me which package is being build. This is as annoying as messages that tell you that you have a new message in some inbox elsewhere. And those messages usually contain a link. Copr messages leave it to me to figure out where to go and what to look at.

I don't mean any disrespect to anyone. But we have been waiting quite long for Copr notifications. But this is as good as no notification at all.

I'd like to see at least the name of the package being build. If possible what triggered the build, e.g. dist-git, manual push via CLI, triggered in Web UI, etc. A link to the build shouldn't be very hard either. I get that even on the command line.

With regards to FMN, I'd like to see better, more versatile filtering. The globs are quite often to simple, forcing one to set up separate rules for each service one likes to receive messages from. Whereas those could easily be combined if the filtering would be more adaptable. Maybe regular expressions isn't too much to ask for? Of course, the ability to filter is also influenced by the quality of the messages.

**Comment by abompard** [comment]
Yeah, this should be reported on Copr's message schemas. I'll try to transfer the issue.
Could you open a different issue to improve FMN's filtering, as in your last paragraph, please?

**Comment by abompard** [comment]
Looks like I can't because I don't own fedora-copr/copr. Do you mind copy-n-pasting your text there please?

**Comment by penguinpee** [comment]
For the Copr part, I think fedora-copr/copr/issues/3237 covers the messages being unhelpful / lacking detail.

I'll open a new ticket for the filtering on the FMN side after I've refreshed my memory a bit more.

**Comment by penguinpee** [comment]
FMN part continued in #1155. Closing.
