### ISSUE TITLE
Delayed notifications have misleading timestamps.

### ISSUE THREAD

**Issue by Rombobeorn** [fedora-infra/fmn#1145]
Like its predecessor, the new notification system can send emails several days after the event happened. Those emails seem to be dated when the notification was converted to email form, and contain no information about when the event happened. The misleading timestamp makes it difficult to figure out whether something actually happened, or whether the notification pertains to an old event that I already know about. (Notifications about Git pushes contain a timestamp in the message body, but I think that's Git's "commit date" or "author date", not the time when the commit was pushed.)

The Date header field in the email should be set to the time when the event happened, not the time when the notification was converted from Fedora messaging form to email form.

According to RFC 5321 the gateway that converts the notification to email form must add a Received field. That's the field that shall contain the time when the conversion happened:
https://datatracker.ietf.org/doc/html/rfc5321#section-3.7.2
https://datatracker.ietf.org/doc/html/rfc5321#section-4.4

**Comment by abompard** [comment]
This time the situation is actually quite different: the SMTP server in the Fedora Infra has had an expired TLS certificate for a few days, delaying the sending of the email notifications. They stayed in the queue until a connection could be established, which lasted a few days, and it's only when being sent out that the Date header is added. That's where we can do something better: a Date header should be added when the notification is generated, not when it's sent.
I think this should be done in [destination.py](https://github.com/fedora-infra/fmn/blob/ffe4e2ffe42d24b40a2b53a74e227860043bed20/fmn/database/model/destination.py#L58) by adding the corresponding header.

**Comment by Rombobeorn** [comment]
And that's why you should add Received. It would have enabled me to see
that the delay was in the email relay chain.

**Comment by abompard** [comment]
I've added a `Date` header in #1226, it was indeed missing. After reading the RFC, I don't think we should add `Received` headers, as those must be added by email gateways, and FMN is an email creator, not a gateway.
The `Date` header should be sufficient to help debug email relay chain issues, as the first `Received` header will be added by the first gateway.

**Comment by Rombobeorn** [comment]
I see you set Date to the time when the message is converted from AMQP form into email form, not the time when the AMQP message was generated. That will still be misleading whenever there is any delay in the AMQP communication.

RFC 5321 makes a distinction between "relaying" (section 3.6) and "gatewaying" (section 3.7). A relay speaks SMTP on both sides. A gateway performs "a translation function between one transport service and another". There is some program that receives messages over AMQP, translates them into the Internet Message Format, and forwards them over SMTP. That program is a gateway in the RFC 5321 terminology. The RFC requires both relays and gateways to prepend a Received field.

**Comment by abompard** [comment]
Good points! I'll amend the PR, thanks.
