### ISSUE TITLE
There is no way to import filters (all or just a single one)

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#115]
FMN supports exporting filters. That is great for backup purposes (if you want to try modifying your filters a lot with an easy way to go back), or irc<->email synchronization purposes (when you want to have the same filters in both channels). However, the second part of this process, **import**, does not seem to be available. So even when I back everything up, I don't seem to have a way to restore my old filters (either overwriting or not overwriting existing ones). I also don't have any way to pick one of my IRC filters and copy it to the email filters list (using export and import for a single filter). So currently, I need to re-create everything manually.

Please add the import button...?

**Comment by ralphbean** [comment]
Good idea.  :)  The export button was designed for a different purpose, but this is a good use case.  Thanks!

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
