### ISSUE TITLE
Pagure filter present in the sources but not in the UI

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fmn#116]
We have rules for pagure: https://github.com/fedora-infra/fmn.rules/blob/develop/fmn/rules/pagure.py but I can't find them in the UI, so I guess we have something wrong in our app :-(

**Comment by ralphbean** [comment]
It is maybe absent from `__init__.py`?

**Comment by pypingou** [comment]
Guess what https://github.com/fedora-infra/fmn.rules/blob/develop/fmn/rules/__init__.py :-)

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/fmn.rules/pull/69
