### ISSUE TITLE
Add an 'agent' to all fedmsg messages

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn#118]
This will let us distinguish between when a user changes they own prefs, and when _we_ change their prefs via an alembic upgrade script.  Then they won't get notifications like "you changed your own prefs!"  when really, _we_ did it.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
