### ISSUE TITLE
Two filters with the same name are bugged

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#120]
If I create two filters with the same name (the can have same or different content), all actions performed on either of them are always applied to the first one. So the second filter can't be disabled, deleted, etc, it always applies to the first one of the same name.

Reproducer:
1. create two filters "Test" with a different rule, so that you can easily distinguish them:

```
Filter Test
 - Rule A

Filter Test
 - Rule B
```
1. See how they got ordered on the main FMN page
2. Try to disable the second one. The first one will get disabled instead.
3. Try to disable the second one again. Nothing happens, because the first one is already disabled and the action is still performed on that one. The second filter is still enabled.

It seems that when performing operations on filters, the filters are matched by their name and not by their ID. Please match them by their ID.

This was discovered as a result of bug #119.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
