### ISSUE TITLE
Weird "notify" argument for "New taskotron task result" rule in certain cases

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#121]
Yesterday we deployed fedora-infra/fmn.lib#59. When I look at the adjusted _Events on packages that I own_ filter, there's a new excluded _New taskotron task result_ rule (which is correct), but it contains an editable option **notify** (defaults to `False`):

![notify](https://cloud.githubusercontent.com/assets/755451/13171769/d8fb1b94-d6f4-11e5-840f-501700affa62.png)

![edit](https://cloud.githubusercontent.com/assets/755451/13171981/0c714326-d6f6-11e5-8586-41b1926f6ea1.png)

Is that a bug or is it intended? Because I have no idea what it is supposed to do. When I add the same _New taskotron task result_ rule into my own custom filter, I do not see such an option there:

![usual](https://cloud.githubusercontent.com/assets/755451/13171788/fb7f62e2-d6f4-11e5-88f0-93deefa19783.png)

I have not yet tried to break FMN by providing an incorrect Python syntax into that field. Should I? :-)

**Comment by ralphbean** [comment]
Totally a bug.  I tried to hack something out to make the db upgrade go faster and wound up with that value in there.  Its harmless, but I will fix it today with a SQL statement.

**Comment by ralphbean** [comment]
This is resolved now.
