### ISSUE TITLE
Anitya rules are missing "When new upstream releases are detected for project name"

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#123]
I want to use FMN to track projects from anitya, which are not packaged in Fedora. Therefore I can't use

```
Anitya | When new upstream releases are detected
Generic | All packages matching a regular expression
```

I guess I could use

```
Anitya | When new upstream releases are detected
Generic | All messages matching a regular expression
```

However, that probably searches everywhere in the message, so if I want to follow a project with some unlucky name, chances are I'll get some false positives. Also, this can't be tested, because "Searching for example messages that match this filter" seems to take eternity and time out, so you don't know even if it actually works or not (not sure what's wrong, because https://apps.fedoraproject.org/datagrepper/raw?topic=org.release-monitoring.prod.anitya.project.version.update is reasonably fast).

I imagine this could be solved (and made easier) by introducing a new rule "When new upstream releases are detected for project name" where you could define a project name as a regular expression (so that you can define more of them), or by modifying the existing rule "When new upstream releases are detected" to allow an optional such argument.

**Comment by ralphbean** [comment]
Would a comma-separated list of "upstream project" names work for you here?

**Comment by kparal** [comment]
Of course, thanks!
