### ISSUE TITLE
Pagure API errors aren't handled well enough

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fmn#1230]
> Looking at [this Fedora devel thread](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/RUTIS3MUFEK2F5YFPDMY2BNMNY46P5QW/), it seems that there is no way, or at least no way that it known in the devel mailing list, to get notifications from all packages where I am a co-maintainer. This is not good, having co-maintainers is much less useful if they are cut off from important events like Koschei build failures.

_Originally posted by @oturpe in https://github.com/fedora-infra/fmn/issues/915#issuecomment-2440150467_

Currently, FMN will retry 3 times if Pagure's API errors out with a 500 error, and after the third time it will return an empty result. This is not good enough. For some users who have a ton of packages (such as `churchyard`), the 500 is almost systematic, and as a result those users can't use FMN. But it also happens on other API calls. I haven't investigated the cause in Pagure.

We can raise the number of attempts to 10, but it brings the cache rebuild time from 1,5 hours to 8 hours which seems too much. I'll try with 5 but this does not seem like a good solution.

This ticket is for investigating a better API error management in FMN.

**Comment by abompard** [comment]
Pinging the original discussion members: @oturpe & @decathorpe

**Comment by decathorpe** [comment]
I've started to receive more relevant notifications again - so it looks like this is working! Thank you 💯

**Comment by oturpe** [comment]
Same here, I am <del>not</del> now receiving Koschei notifications. Thank you!

**Comment by abompard** [comment]
Hey @oturpe ! Could you give me an example of a koschei build that should have notified you?

**Comment by decathorpe** [comment]
I think that possibly should have been `s/am not/am now/` :)

**Comment by oturpe** [comment]
Correct, there was a typo in my comment. I just wanted to say that my problem is fixed.
