### ISSUE TITLE
Digest not working?

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/fmn#125]
It's been a while that I don't receive any digest email and I start thinking that they aren't working anymore.
If I set fmn to send all single messages I receive them.

I don't know if something got broken after the modifications which added the "summary". I remember to have received at least a couple of digests with the summary, so I think that's not the cause.

**Comment by jeremycline** [comment]
@mattiaverga Is this still an issue?

**Comment by mattiaverga** [comment]
No sorry, I completely forgot it.
