### ISSUE TITLE
RFE: tooltip hint which shows the kind of rule for matched notifications

### ISSUE THREAD

**Issue by raveit65** [fedora-infra/fmn#126]
Fmn displays matched messages below a rule set on the left side.
A tooltip hint which kind of rule triggered this messages would be very helpful to configure a rule set, especially if you want to improve the default rule set.
For some messages it's very difficult to say from which rule they was triggered. Ie.
'pkgdb created branch 'f24' for the 'system-config-keyboard' package'
I expected that this was from a pkgdb rule and not from a git rule.
Thank you

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
