### ISSUE TITLE
Bugzilla notifications from "anything involving my username"

### ISSUE THREAD

**Issue by swt2c** [fedora-infra/fmn#127]
Recently (probably since Bugzilla got hooked up to fedmsg), I started to get fedmsg notifications such as: 

updates commented on RHBZ#1312820 'Lots of WARNING: unable to delete
selinu...'

from the "anything involving my username" filter.  Is this expected?

**Comment by voxik** [comment]
I think I enabled all the filters to remove the notifications, but I still get emails such as

```
ansilva@redhat.com commented on RHBZ#1206936 'Laptop does not resume from hibernate, b...'
    https://bugzilla.redhat.com/show_bug.cgi?id=1206936
```

I think there is bug somewhere ...

**Comment by nirik** [comment]
yes, this is expected. You should add to the 'anything involving your username' filter a 'all bugzilla messages' and then negate it (so the rule will become: anything involving your username and NOT bugzilla messages).

**Comment by swt2c** [comment]
Yes, that is what I eventually figured out.  Thanks.
