### ISSUE TITLE
Some emails sent are too big

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn#128]
Noticed this traceback from the backend mailer today:

``` python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fmn/consumer/producer.py", line 49, in poll
    self.work(session)
  File "/usr/lib/python2.7/site-packages/fmn/consumer/producer.py", line 94, in work
    self.manage_batch(session, backend, pref)
  File "/usr/lib/python2.7/site-packages/fmn/consumer/producer.py", line 136, in manage_batch
    backend.handle_batch(session, recipient, queued_messages)
  File "/usr/lib/python2.7/site-packages/fmn/consumer/backends/mail.py", line 178, in handle_batch
    topics, categories, usernames, packages)
  File "/usr/lib/python2.7/site-packages/fmn/consumer/backends/mail.py", line 111, in send_mail
    to_bytes(email_message.as_string()),
  File "/usr/lib64/python2.7/smtplib.py", line 730, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (552, '5.3.4 Message size exceeds fixed limit', 'notifications@fedoraproject.org')
```

We should:
- Figure out what that fixed limit is.  Ask the admins.
- Update the code in `fmn/consumer/backends/mail.py` to detect if the message is too large and, if it is:
- Truncate the message (or split it up.. or something like that).

**Comment by nirik** [comment]
Limit on bastion seems to be: 
message_size_limit = 20971520

we could increase it, but man, thats a pretty big email...

**Comment by pypingou** [comment]
Last time it was an message based on an action of rdieter with these info
`
'total': {u'deletions': 2, u'files': 12086,
+u'additions': 843420, u'lines': 843422}}, u'name': u'Rex Dieter', u'rev': u'2572b7e4e89eb60068ddc82679c58dabdcad71d9', u'agent': u'rdieter', u'summary': u'KDE
+Frameworks 5.21.0', u'repo': u'breeze-icon-theme', u'branch': u'epel7', u'path': u'/srv/git/repositories/rpms
 /breeze-icon-theme.git', u'seen': False, u'message': u'KDE Frameworks 5.21.0\n', u'email': u'rdieter@.... 'topic': u'org.fedoraproject.prod.git.receive'}`

**Comment by pypingou** [comment]
I'm seeing that there are a lot of svg files in this repo, so git can diff them, which means we have a diff for each and every file in there.

**Comment by pypingou** [comment]
And this is the commit in cgit: /!\ beware that it might fill up your memory :)
http://pkgs.fedoraproject.org/cgit/rpms/breeze-icon-theme.git/commit/?h=epel7&id=2572b7e4e89eb60068ddc82679c58dabdcad71d9

**Comment by jeremycline** [comment]
@puiterwijk this sounds like what you fixed in https://github.com/fedora-infra/fmn.consumer/pull/88. Can this be closed now?

**Comment by puiterwijk** [comment]
Yes, this is fixed.
