### ISSUE TITLE
Notify package maintainers if a package is orphaned that one of their packages depends on

### ISSUE THREAD

**Issue by tyll** [fedora-infra/fmn#129]
To make it more likely that package maintainers notice when a package is orphaned that one of their packages depends on, I would like to write a notification system for this. The idea is to listen for fedmsg messages about orphaned packages, calculate which packages directly depend on it and then notify the maintainers of these packages. Also if the package gets adopted again, notify them again so they know nothing needs to be done anymore. Since fmn is already a notification system, I think this would be a good addition for it.

The script https://pagure.io/releng/blob/master/f/scripts/find_unblocked_orphans.py#_358 contains code to identify dependent packages.

**Comment by pypingou** [comment]
Maybe mdapi could be used as source of info for the dependencies

**Comment by tyll** [comment]
for this we actually need the reverse deps, would this be something that can be added to mdapi?

**Comment by pypingou** [comment]
I think we should add it yes

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
