### ISSUE TITLE
disable rather than delete filters

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#13]
As a newcomer, I'm not sure I want to delete some of the pre-defined filters, but I'd like to disable some of them and delete them if I find out I'm not missing anything. Please allow to disable filters, it's much more user friendly than outright deleting them.

**Comment by ralphbean** [comment]
This requires that we first add a database column to fmn.lib indicating that a filter is disabled or not.

We need:
- [x] to add that column in fmn.lib
- [x] to add an alembic upgrade script in fmn.lib to add that column
- [x] load_preferences in fmn.lib should make use of the new column and not return the filter if it is disabled
- [x] the UI in fmn.web needs a button and stuff to turn this on and off

**Comment by pypingou** [comment]
These three commits should address the first two items and maybe the third one (to be confirmed by @ralphbean )

**Comment by rossdylan** [comment]
I'm currently working on the bits in fmn.web to enable/disable filters. Patch should up today

**Comment by ralphbean** [comment]
@pypingou can you submit a pull request to discuss the code?  I left a comment in fedora-infra/fmn.lib@5059c8776c6ddc16c2f037e40dd0af849e9ca673

**Comment by ralphbean** [comment]
Closed by fedora-infra/fmn.lib#15 and fedora-infra/fmn.web#31
