### ISSUE TITLE
case sensitivity for regular expressions?

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#130]
In FMN there's this rule:

> All messages matching a regular expression
> Use this rule to include messages that bear a certain pattern. This can be anything that appears anywhere in the message (for instance, you could combine this with rules for wiki updates or Ask Fedora changes to alert yourself of activity in your area of expertise).
> (i.e., (beefy miracle)).

Can you please clarify whether the matching is case sensitive or insensitive? Thanks.

(The same thing applies for `All packages matching a regular expression` rule).

**Comment by pypingou** [comment]
Code-wise it is at:
https://github.com/fedora-infra/fmn.rules/blob/develop/fmn/rules/generic.py#L165
and
https://github.com/fedora-infra/fmn.rules/blob/develop/fmn/rules/generic.py#L181

(which only partly answers the question and doesn't solve the RFE :))

**Comment by kparal** [comment]
Reading the source code, it seems it is case sensitive? Could you add an option to the rule to have it case insensitive (or maybe it even makes sense to have it on by default?). Thanks.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
