### ISSUE TITLE
Pending group members get notifications

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/fmn#131]
Based on this fedmsg:

https://apps.fedoraproject.org/datagrepper/id?id=2016-5c4fe273-7936-4f21-aa92-43b9ca616e59&is_raw=true&size=extra-large

My colleges got a notification, with they default and only filter _A particular user's packages (any acl)_. However they are not in pypy's ACLs in any way. They applied for python-sig membership, that's maybe a reason why they get it, but their membership in that group was not approved yet.

FAS users torsava and cstratak

**Comment by ralphbean** [comment]
Maybe `fas.group_members` here is returning the pending members as well when it should not?

https://github.com/fedora-infra/fmn.rules/blob/develop/fmn/rules/utils.py#L186-L205

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
