### ISSUE TITLE
filter github PR notifications per project

### ISSUE THREAD

**Issue by jhrozek** [fedora-infra/fmn#132]
Hopefully this is not a bug, but just my lack of understanding how the app works.

We have a mirror of a fedorahosted project set up on github. I would like to receive notifications about PRs only for this project -- but in the notifications app, I was only able to set up notifications for all github PRs.

How do I get notifications only about one selected github repo?

**Comment by pypingou** [comment]
So the way I do it is via:

```
- Continuous integration status (github.com)
+ All Fedora-related GitHub activity
- Deleted tags and branches (github.com)
+ All messages matching a regular expression ``(fedora-infra|pypingou)``
- A particular user: ``pingou``
```

In other words:
- Keep all the github messages
- Keep all messages matching the regex `(fedora-infra|pypingou)` (the two repo/groups I'm interested in)
- Ignore all CI notification
- Ignore tags and branches deleteion
- Ignore all the action I do

Does this help?

**Comment by jhrozek** [comment]
Thanks for the reply. I think it does, I need to set this up and then report back, but it sounds plausible

**Comment by jeremycline** [comment]
@jhrozek I'm going to close this since it sounds like this is possible at the moment. Please re-open this issue if you're still having problems.
