### ISSUE TITLE
Missing i18n in subjects of the sent emails from notifications@fedoraproject.org

### ISSUE THREAD

**Issue by fredhgl** [fedora-infra/fmn#133]
Hi,
I'm receiving emails from notifications@fedoraproject.org without i18n in the subjects

The subject sent from notifications@fedoraproject.org was:
fredlima posted "V??deo sobre a hist??ria da antiga distribui????o Red Hat Linux at?? o RHEL"

but it will be correct if it was sent like this:
fredlima posted "Vídeo sobre a história da antiga distribuição Red Hat Linux até o RHEL"

the message body text is correct.

can you take a look at this issue?
thank you in advance

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
