### ISSUE TITLE
Copr builds failing has wrong link with group repos

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/fmn#134]
I just got this e-mail:

> Package:  python26-2.6.9-1.fc26
> COPR:     @python/python26
> Built by: churchyard
> Status:   failed
> ID:       00450811
> 
> Logs:
>   Build:     https://copr-be.cloud.fedoraproject.org/results/@python/python26/fedora-23-i386/00450811-python26/build.log.gz
>   Root:      https://copr-be.cloud.fedoraproject.org/results/@python/python26/fedora-23-i386/00450811-python26/root.log.gz
>   Copr:      https://copr-be.cloud.fedoraproject.org/results/@python/python26/fedora-23-i386/build-00450811.log
>   Mockchain: https://copr-be.cloud.fedoraproject.org/results/@python/python26/fedora-23-i386/00450811-python26/mockchain.log.gz
> Results:     https://copr-be.cloud.fedoraproject.org/results/@python/python26/fedora-23-i386/00450811-python26/
> Repodata:    https://copr-be.cloud.fedoraproject.org/results/@python/python26/fedora-23-i386/repodata/
> 
>   https://copr.fedoraproject.org/coprs/@python/python26/build/450811/

Note that the last link is wrong (404). It shoudl have been:

https://copr.fedorainfracloud.org/coprs/g/python/python26/build/450811/

Other links are correct.

I've been trying to find out where is the mail generated but could not, sorry :(

**Comment by pypingou** [comment]
It's likely part of fedmsg_meta_fedora_infrastructure

**Comment by ralphbean** [comment]
Yup! The [long_form](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/coprs.py#L76-L92) method there is used to generate email bodies.

**Comment by hroncok** [comment]
long_form method there [ends with](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/coprs.py#L48) `Repodata:` line

long_form only seems defined in that repo, not called, so I don't see how the last link even got there.

**Comment by ralphbean** [comment]
Yup.

The FMN backend calls `fedmsg.meta.msg2long_form(...)` here:  https://github.com/fedora-infra/fmn.consumer/blob/develop/fmn/consumer/backends/mail.py#L129

That in turn calls the `long_form` method of that Processor here:  https://github.com/fedora-infra/fedmsg/blob/develop/fedmsg/meta/__init__.py#L239-L250

**Comment by ralphbean** [comment]
> long_form method there ends with Repodata: line

Ah, that last link must be the output of the [link method defined here](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/coprs.py#L130-L145).  You can see how it gets called and tacked on with `+ '\n\t' + link` [here in fmn.consumer](https://github.com/fedora-infra/fmn.consumer/blob/develop/fmn/consumer/backends/mail.py#L135).
