### ISSUE TITLE
Consolidate the various RabbitMQ connection creation methods

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#144]
There are now several places in the code of `fmn.sse` and `fmn.consumer` where a connection to RabbitMQ via Twisted is used. Both packages create and configure a connection. It would probably be best to create a class here to handle the creation and configuration of the connection especially since I believe neither place currently makes use of Twisted's  [re-connection support](https://twistedmatrix.com/documents/current/core/howto/clients.html#reconnection) (unless I misunderstand how the ClientCreator API works). It looks like the [endpoints](https://twistedmatrix.com/documents/current/core/howto/endpoints.html) API is what we want to use.
- [ ] Create a general purpose class to create and configure a `pika.TwistedProtocolConnection`
- [ ] Migrate `fmn.consumer.consumer` to use the new class
- [ ] Migrate `fmn.consumer.digests` to use the new class
- [ ] Migrate `fmn.sse` to use the new class

Moved from https://github.com/fedora-infra/fmn.lib/issues/65

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
