### ISSUE TITLE
fmn.lib depends on html5lib

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#145]
According to the comments [here](https://github.com/fedora-infra/fmn.lib/blob/0.8.2/fmn/lib/__init__.py#L155-L165), this functionality should be moved to `fmn.web` which seems reasonable given my understanding of the code. It appears to mark up docstrings automatically which is only really useful to `fmn.web`.

This feature depends on `html5lib`, so we should move this functionality to `fmn.web` (along with the dependency) and remove the dependency on `html5lib` from `fmn.lib`.

Moved from https://github.com/fedora-infra/fmn.lib/issues/64

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
