### ISSUE TITLE
Many synchronous calls are occuring within Twisted in the backend

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#148]
The consumer backend has a little Twisted application that handles all the work. However, there are quite a few calls that appear to be synchronous. 

For example, it looks like the database is queried in fmn/consumer/backend.py#L199 and I believe that's synchronous. 

The backend class's `handle` function is called in fmn/consumer/backend.py#L189 and I can see that at least the email's handler is synchronous. All this means that this code is executing in the Twisted reactor and is blocking everything to perform IO, which is what Twisted is meant to help avoid.

This has fairly large performance implications.

**Comment by jeremycline** [comment]
Nearly all blocking calls have been removed from the backends (now in ``fmn/delivery/backends``) with the exception of a database query in the IRC backend.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
