### ISSUE TITLE
A rule to include messages from specific people or anyone except for specific people

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#15]
There are a lot of nice filters that relate to my packages, like _New sources uploaded for packages that I own_. However, there's a missing piece of the puzzle - I would like to received such notifications only for actions that _I didn't make_. I don't want to be notified that I uploaded new sources, or created a new git branch or whatever, because _I know that_. However, I would be very interested in seeing these notifications if a co-maintainer/provenpackager/someone else did that.

Please add these two generic rules:

> User filter
> Include all messages for which the author of the event is: _fasnick_

and 

> User filter
> Include all messages for which the author of the event is not: _fasnick_

I would use the second one and add it to the new sources/new branch/etc filters to filter our my actions. The first rule might also be useful for people who want to get notified of someone else's actions.

**Comment by kparal** [comment]
Oh, the first rule is already present, it's called *All messages for a certain user *. So only the second rule needs to be added.

**Comment by pypingou** [comment]
Note: the idea is that bodhi/FAS/pkgdb2... at some point might/will stop sending emails themselves, thus this default set of filters.

**Comment by kparal** [comment]
Yeah. But people still generally don't want confirmations of their own actions (at least I don't want), don't you agree? So for example Bodhi emails telling me that I have added a comment to an update really annoy me. And that's something we could improve with fmn - we just need a rule to filter out our own actions.

**Comment by pypingou** [comment]
Oh, I agree ^ ;-)
