### ISSUE TITLE
Document how to monitor the work queues

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#153]
RabbitMQ provides ways to monitor it and its queues (the built-in management plugin for one). It'd be good if we made a note that this was possible in our documentation.

The script we currently use in Fedora Infrastructure is
```
#!/bin/python
import sys
import requests

url = 'http://localhost:15672/api/queues/%%2f/%s' % (sys.argv[1])

r = requests.get(url, auth=('guest', 'guest')).json()
consumers = r['consumers']
messages = r['messages']

msg = 'Messages in queue: %i (%i consumers)' % (messages, consumers)

if consumers < 1:
    print 'CRITICAL: No consumers: %s' % msg
    sys.exit(2)

if messages > sys.argv[2]:
    print 'CRITICAL: %s' % msg
    sys.exit(2)

if messages > sys.argv[3]:
    print 'WARNING: %s' % msg
    sys.exit(1)

print 'OK: %s' % msg
sys.exit(0)
```

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
