### ISSUE TITLE
Separate generic rules from service rules

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#16]
Currently it's a bit confusing that generic rules (e.g. _All messages for a certain user_) are mixed with service rules (e.g. Koji rules, Bodhi rules). It would be much easier to navigate if you created a separate container for _Generic rules_ and then a container for each services. I imagine this as a expandable box called e.g. Koji. If I expand it using an arrow, I see all available rules related to Koji.

This way it will take less space and be more readable. The generic filters box should be the first one displayed.

**Comment by ralphbean** [comment]
Good feature.  I like it.

Technically, we can implement this by figuring out which submodule of `fmn.rules` the rule comes from.  So, `fmn.rules.generic` rules come first, and then the rules from `fmn.rules.bodhi`, and then `fmn.rules.wiki` and so on.  We can just put 'generic' first and then do the rest alphabetically.

**Comment by pypingou** [comment]
@ralphbean I worked on that a while back, I had them organized as you mentioned and presented in an accordion structure. No idea where the code went though ^^
