### ISSUE TITLE
Run tests with tox and pull the style test out in favor of a tox flake8 test

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#163]
This allows the style to optionally be tested separately or specifically skipped. Right now we don't run the tests in the EPEL7 build because the old flake8 doesn't like the code (even though newer flake8 does). This change would let us just run the tests and not the style test on the downstream EPEL7 build.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
