### ISSUE TITLE
Empty email from pagure

### ISSUE THREAD

**Issue by omajid** [fedora-infra/fmn#166]
I received an email from notifications@fedoraproject.org that has no subject and the body just says pagure.io.

Mail headers:

    Return-Path: notifications@fedoraproject.org
    To: $MY_ACTUAL_EMAIL_ADDRESS
    From: notifications@fedoraproject.org
    X-Fedmsg-Topic: io.pagure.prod.pagure.request.assigned.added
    X-Fedmsg-Category: pagure
    X-Fedmsg-Username: omajid
    Subject:
    MIME-Version: 1.0
    Content-Type: text/plain; charset="utf-8"
    Content-Transfer-Encoding: base64
    Message-Id: <20170217150720.097F6605E1EC@bastion01.phx2.fedoraproject.org>
    Date: Fri, 17 Feb 2017 15:07:20 +0000 (UTC)
    

Mail body:

            https://pagure.io
    
    --
    You received this message due to your preference settings at
    https://apps.fedoraproject.org/notifications/omajid.id.fedoraproject.org/email/48379

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
