### ISSUE TITLE
Is it possible to get notifications for all activity on a Github repo (or list of repos)?

### ISSUE THREAD

**Issue by mikebonnet** [fedora-infra/fmn#167]
There are a bunch of options for what kind of activity on a Github repo to be notified about. However, I can't find a way to get all activity or a given repo or set of repos. The alternative is "All Fedora-related Github activity", which is overkill. If there's a way to filter that feed to specific repo(s), that would work.

**Comment by pypingou** [comment]
I use the combo of:
- All fedora-related GitHub activities
- All messages matching a regex: pattern: (fedora-infra|pypingou)
- Not a particular user: pingou
- Not delete tags and branches
- Not CI status

**Comment by mikebonnet** [comment]
Thanks @pypingou , I'll try that! Do you know what data the regex is matched against?

**Comment by pypingou** [comment]
tbh I do not, I'm not sure if it's against the whole message or just some parts of it :s

**Comment by mikebonnet** [comment]
Looks like it's matched against the raw JSON. I've got a regex that's working. Thanks!
