### ISSUE TITLE
IRC messages when offline

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#17]
Please clarify whether the IRC bot will inform me about all the events that happened during the time I was offline, or whether I receive only realtime messages and when I'm offline I'll lose the notifications. Currently it's not clear from the IRC Preferences description. Thanks.

**Comment by ralphbean** [comment]
At the moment, it does not queue them -- you lose the notifications.

We could conceivably queue them with relatively little work.  There is already a queuing mechanism for batch delivery we could leverage.

**Comment by ralphbean** [comment]
Thinking about this further..

It used to be that if the irc bot had any problems at all, it would drop the messages.

Now, if the irc bot itself is offline for some reason (network trouble), then it will queue messages for users and then send them once it gets back online.

However, detecting that a user is offline is more tricky and would involve a stateful dance between 1) trying to send the message, 2) hearing back that the user was not offline, 3) and only then queueing the message.

It is difficult enough, I think that the best option is just to explain in the UI that messages sent to you when you are offline will just be dropped.

**Comment by nirik** [comment]
There is also memoserv on freenode: 
https://toxin.jottit.com/freenode_memoserv_commands

But most people don't know anything about it and might be confused by it telling them they have memos. They would also need to be identified with freenode. Just a thought.

**Comment by ralphbean** [comment]
Hm.  We do already require that they are registered and identified with freenode when they first setup their fmn account.  I'm a little wary of depending on memoserv though.  If we started sending tons of memos to users who never get online again, would the freenode staff be miffed?

**Comment by nirik** [comment]
Yeah, not sure if it would cause too much hassle. ;( 

Perhaps we are best off just saying that if you aren't available messages are dropped. 

Or... could we offer a 'if not on irc, fallback to email' option?

**Comment by kparal** [comment]
> Or... could we offer a 'if not on irc, fallback to email' option?

I think that's a great idea.
