### ISSUE TITLE
It is possible to get a filter that matches basically all messages on the bus

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/fmn#173]
If I create a filter but all the rules in it are set to Negated, it seems to match every message sent on the bus.
Which is... kind of overwhelming.

We should probably not allow (or ignore so people can continue setting up) filters with only negated rules.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
