### ISSUE TITLE
Bad notification

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/fmn#176]
Hi,

I just received tons of notifications:

* ralph requested package php on branch master
* ralph requested package php on branch f26
* ralph changed ralph's 'watchcommits' permission on php (master) to 'Approved'
* ..

While "php" already exists.

LInk in notification point to https://admin.fedoraproject.org/pkgdb/package/php/ (so obviously wrong)

I think this is related to modularization.

Please fix this

P.S. I also received notification from git-dist with same issue (don't know if this have be fixed)

**Comment by jeremycline** [comment]
Related to https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/pull/423

**Comment by jeremycline** [comment]
Okay, so here's what's happening:

1. There are now multiple packages with the same name under different namespaces: [rpms/php](https://admin.fedoraproject.org/pkgdb/package/modules/php/) which you have ACLs to, [modules/php](https://admin.fedoraproject.org/pkgdb/package/modules/php/) which @ralphbean made this morning, etc).

2. FMN is using ``fedmsg.meta.msg2packages`` to get the packages message relates to. This is just package names, and has no concept of namespaces. (e.g. for you ``php`` is in the list).

Now, FMN will need an update to take namespaces into account when finding out what [packages a maintainer has](https://github.com/fedora-infra/fmn/blob/develop/fmn/rules/utils.py#L163), but we also need ``fedmsg.meta.msg2packages`` to know about namespaces, which means changing the fedmsg.meta API.

**Comment by ralphbean** [comment]
Changing the fedmsg.meta API for `msg2packages` will mean updating usage of that function in a *lot* of places (datanommer, datagrepper, FMN, bodhi, others?).

- Maybe the easier route would be to add new `msg2modules` or `msg2containers` functions?
- Another option, augment msg2packages with an optional `msg2packages(..., namespace='rpms')` default parameter.  Old systems will work as they did, and we can slowly patch them over time to intelligently handle different namespaces as they need to.

(FWIW, i think I like option 2 more).

**Comment by jeremycline** [comment]
Option 2 sounds good to me. Then on the FMN end we just need to adjust our function that queries pkgdb2 slightly (I think). I'll take a swing at implementing option 2 and the FMN change today.
