### ISSUE TITLE
Allow group admins to configure their group's notification profile

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#179]
Related to #178, groups would need to be able to create and configure filters for their notifications (which would appear in Hubs). It'd be good if this was done in a way that didn't really tie FMN to Fedora specifically since it'd be nice for it to be a portable, general companion to fedmsg.

I haven't done any real research for this, so the first task we need to do for this issue is figure out the details of the desired workflow and how it would fit into what we have now.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
