### ISSUE TITLE
offer a 'if not on irc, fallback to email' option

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn#18]
This came up in issue #17

**Comment by kparal** [comment]
@pypingou According to your talk at DevConf, I got the impression that this is already implemented. But I can't find such an option in FMN. So, is it implemented, or not yet? :) Thanks.

**Comment by pypingou** [comment]
Hi Kamil, I do not think this is already there, sorry if I gave the wrong impression in my presentation

/me will have to check youtube to find out how I gave this impression

**Comment by kparal** [comment]
No problem, I have just misunderstood then :)

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
