### ISSUE TITLE
Increase max characters in the "Anything regarding a particular "upstream project" filter

### ISSUE THREAD

**Issue by mnhauke** [fedora-infra/fmn#187]
I'm using the "Fedora Notifications" webapp to get notified when there's a new upstream release from packages I'm interested in.
It's working well so far until i started to add more packages to the "Anything regarding a particular "upstream project"-filter where you can specify a comma-separated list of upstream project names.

There seems to be a max of number of characters you can specify in this list...
238 chars -> OK
245 chars -> "Internal Server Error" from the webservice

The limit seems to be hardcoded...
https://github.com/fedora-infra/fmn/blob/develop/fmn/lib/models.py#L262-L263

Maybe the limit could be increased to 1024 or even 2048 ?

**Comment by pypingou** [comment]
The simplest way would be to make this a Text() field, thus unlimited. If there are no index on it, it's the easiest fix :)

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
