### ISSUE TITLE
Move the critical tasks for taskotron rules to a configuration file

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#199]
Right now the [list of critical tasks](https://github.com/fedora-infra/fmn/blob/842941ea69f0506bda410de0bb68e29861dfeee5/fmn/rules/taskotron.py#L5) for taskotron rules is a constant in the code. It would be better if this were part of the configuration file.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
