### ISSUE TITLE
Support resend IRC confirmation

### ISSUE THREAD

**Issue by ctubbsii** [fedora-infra/fmn#20]
For some reason I missed the confirmation (maybe nick wasn't registered when I asked for confirmation), but now I can't add the new IRC nick, because it says it's already added, but stuck in this invalid confirmation state.

A button should be available to try again, or to remove an invalid IRC nick, so one can try adding it again.

**Comment by ralphbean** [comment]
Agreed there should be a button allowing you to start over.  For the mean time, I have deleted your 'invalid confirmation record' so you can try again.

**Comment by ctubbsii** [comment]
Hey, thanks!

**Comment by lmacken** [comment]
I just hit this issue as well. My client had appended an underscore to my nick so I didn't get the initial confirmation message. Above the IRC nick field it now says `Your confirmation for lmacken is invalid.`, and inputting my nick again yields `{"reason": "That value is already claimed."}`
