### ISSUE TITLE
kwarg_function_key_generator requires dogpile.cache >= 0.6.2

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#200]
I used dogpile.cache's `` kwarg_function_key_generator``[0], but it [was added in 0.6.2](http://dogpilecache.readthedocs.io/en/latest/changelog.html#change-0.6.2-feature) so it doesn't work on EL 7.

We need to come up with a replacement.

[0] https://github.com/fedora-infra/fmn/blob/8b3b69b9eb7ef9a0c40ccf066879f447af29a0d1/fmn/lib/__init__.py#L10

**Comment by ralphbean** [comment]
>  it doesn't work on EL 7.

Can we update it in epel7?

We can certainly update it in the epel7-infra tag.

The infra-sig owns it, too.  https://apps.fedoraproject.org/packages/python-dogpile-cache/overview/

**Comment by jeremycline** [comment]
We could, although 0.6.0 removed some [classes](http://dogpilecache.readthedocs.io/en/latest/changelog.html#change-0.6.0) so anyone depending on those being around (even though they _are_ deprecated) will break. It's obviously appealing to me, but...

Edit: Also worth noting that @bowlofeggs nacked a proposed update for F24: https://bodhi.fedoraproject.org/updates/FEDORA-2016-9db7521f4b

**Comment by ralphbean** [comment]
In that case, I'd recommend building for `epel7-infra` as the path of least resistance.

**Comment by jeremycline** [comment]
https://github.com/fedora-infra/fmn/pull/201 is a potential solution, but I'm not exactly sold on it.

**Comment by jeremycline** [comment]
Building it into epel7-infra will still hit other apps we have though, right? @bowlofeggs, what problems did you run into, I seem to recall you having some non-trivial problems with dogpile.cache.

**Comment by bowlofeggs** [comment]
On Thu, 2017-06-01 at 10:45 -0700, Jeremy Cline wrote:
> @bowlofeggs, what problems did you run into, I seem to recall you
> having some non-trivial problems with dogpile.cache.

I can't remember what problems I might have hit with dogpile.cache.
