### ISSUE TITLE
Make fmn.rules.utils._get_packagers_for namespace-aware.

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn#208]
Currently, a query to that function returns packagers associated with a package, given the package name.

But, if I request the packagers associated with 'httpd', do I get the packagers associated with rpms/httpd or the packagers associated with modules/httpd, or both?

In the first place the function needs to be modified to be namespace aware.

In the second place, all uses of the function need to be (thought through and) modified to provide appropriate namespaces.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
