### ISSUE TITLE
Adjust fmn.rules.utils._get_pagure_packages_for to handle the watched state

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn#209]
This depends on https://pagure.io/pagure/issue/2421 being implemented and deployed first.

The "watched" flag isn't currently handled at all in fmn.rules.utils.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
