### ISSUE TITLE
Use Pagure client bindings rather than the REST API directly

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#213]
#206 introduced some usage of the Pagure API. It would be best to use Python client bindings, if possible. [An issue has been filed against Pagure to track client bindings](https://pagure.io/pagure/issue/2448).

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
