### ISSUE TITLE
Allow the topic fmn listens to to be configurable

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#216]
FMN currently listens to everything (``b''``) on all the ZeroMQ sockets it connects to. It should be configurable so we filter for production (``b'org.fedoraproject.prod'`` for example).

This should accept either a unicode string or list of unicode strings.

**Comment by pypingou** [comment]
We're going to have to fix this before we can push the CI fedmsg messages onto the Fedora production bus (since Fedora has literally two buses one for prod and one for stg).

(Trying to see if we couldn't fix this at the centos' level which may be quicker/simpler)

**Comment by jeremycline** [comment]
Done. There needs to be a release anyway with that Pagure stuff, so it shouldn't be too much trouble.
