### ISSUE TITLE
Write tests for the fmn.web.app module

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#219]
The web application has 0% test coverage and really needs tests. We need to

- [ ] Set up a base test that provides tests with a Flask application it can modify and use as it sees fit

- [ ] Set up a test database which is fresh and clean for each test

- [ ] Write tests for the entire flask application and document all its APIs.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
