### ISSUE TITLE
IRC mechanism should not be shown as "active" if no nick is configured

### ISSUE THREAD

**Issue by keszybz** [fedora-infra/fmn#22]
This is a continuation of issue #12. IMHO the setup screen is still very unclear, and it is easy to miss that it is necessary to enter a nick. The place to enter the IRC nick should be at the very top of the page, and the status should not be shown as "active" when it is actually not working w/o further configuration.

**Comment by ralphbean** [comment]
Good points all.

**Comment by ralphbean** [comment]
This should be quite improved in the next 0.3.0 release.
