### ISSUE TITLE
How to add a filter for new ask.fp.o with certains contents

### ISSUE THREAD

**Issue by keszybz** [fedora-infra/fmn#23]
I'd like to get notifications for questions on ask.fp.o about systemd. Maybe it's a documentation issue or PEBKAC, but I don't see how I can add a filter like that.

**Comment by ralphbean** [comment]
It's probably just not possible yet... but we can do it!

We probably need to add a new "generic rule" that let's you filter messages by a regex, so you can build a filter that triggers if 1) the message is an ask.fp.o message and 2) the word 'systemd' appears anywhere in there.

**Comment by ralphbean** [comment]
So, that regex rule is in now, so this should be totally possible.  I'll need to write a blogpost on it to educate people how to use it.
