### ISSUE TITLE
Digest IRC Output

### ISSUE THREAD

**Issue by abadger** [fedora-infra/fmn#24]
Idea for the fmn irc output:  digest the output with a paste-like service.

Something like:

```
pkgdb.acl.update -- toshio changed toshio's 'approveacls' permission on python-json (el5) to 'Obsolete' 17 minutes ago [and 20 other pkgdb.acl.updates http://fmn-digests.fedoraptoject.org/52]
```

Maybe use a random value as ID if we're worried about privacy.

**Comment by relrod** [comment]
c.f. https://github.com/fedora-infra/datagrepper/issues/132

**Comment by ralphbean** [comment]
This is totally possible now....
