### ISSUE TITLE
The FMN backend service hangs when stopped if messages are in the delivery queue

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#247]
Something in the delivery service isn't shutting down cleanly if there are messages in the queue, it seems. It hangs until systemd ends it forcibly.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
