### ISSUE TITLE
Refactor the IRC backend to wait on a client connection rather than raising an exception

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#249]
Rather than raising an exception when there are no IRC clients, the IRC backend should wait for a connection to be established. If the connection fails due to a timeout, it's probably okay to raise an exception so the message is nacked and the connection is retried. However, it doesn't make sense to immediately fail because async IO is what twisted is all about.

Not doing this means starting the backend will result in a bunch of errors because there's no client yet.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
