### ISSUE TITLE
RFE: Notifications from COPR should include build ID

### ISSUE THREAD

**Issue by nonamedotc** [fedora-infra/fmn#25]
It would be really nice if the notifications emails corresponding to COPR activities include build IDs.

I received this in the email - 

``` html
copr.build.end -- nonamedotc's xfce411 copr build finished fedora-rawhide-i386 with 'failed'
https://copr.fedoraproject.org/coprs/nonamedotc/xfce411/
```

Before the email arrived, I noticed a failed build, fixed the issue and requested a new build after which I received this email. Without the build ID, it's a bit hard to say what is going on. Please consider.

Thanks for FMN by the way! It is very convenient. :+1:

**Comment by ralphbean** [comment]
Lucky for us, the raw fedmsg messages coming from copr look like they already contain the build id.  See this one for example:

https://apps.fedoraproject.org/datagrepper/id?id=2014-eff97f49-edbd-4148-a0ae-5756717c8b22&is_raw=true&size=extra-large

@nonamedotc, can you tell me more precisely how you would like the message to look?  Perhaps we just add the build id to the link like this:

```
copr.build.end -- codeblock's ghc-78-everything copr build finished fedora-rawhide-i386 with 'failed' 
https://copr.fedoraproject.org/coprs/codeblock/ghc-78-everything/build/28812/
```

**Comment by nonamedotc** [comment]
Hi @ralphbean,
Thanks for your reply. I see this line in the fedmsg output

``` bash
 "build": 28812,
```

This information would be sufficient. The message could be something like

``` html
copr.build.end -- nonamedotc's xfce411 copr build <BUILD ID> finished fedora-rawhide-i386 
with 'failed' - https://copr.fedoraproject.org/coprs/nonamedotc/xfce411/
```

It would be nice to also include the srpm name. But, I do not see it the raw fedmsg and I am not sure how difficult it would be.

**Comment by nonamedotc** [comment]
Oops! I did not read the full comment. Link to the build directly would be perfect. :+1:

Please ignore my previous comment!

**Comment by ralphbean** [comment]
> Link to the build directly would be perfect.

Cool.  I think we're good-to-go since fedora-infra/fedmsg_meta_fedora_infrastructure#134 has been merged.  It still needs to be released and deployed, but I'm going to go ahead and close this ticket.  It should be working for you soon (the next week).

**Comment by nonamedotc** [comment]
Thanks!
