### ISSUE TITLE
Add a results backend for Celery so task results are recorded

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#250]
It'd be nice to know what tasks succeeded and what tasks failed. We should add a [celery SQLAlchemy backend](http://docs.celeryproject.org/en/latest/userguide/tasks.html#database-result-backend) for FMN. Additionally, we should add a celerybeat task to reap old tasks from the database (trim it to, say, the last 7 days by default).

Once we do that, we should re-evaluate the celery tasks and what they should return so we can easily debug who got sent what when.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
