### ISSUE TITLE
Workers crash occasionally crash on startup when tasks are in the queue

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#257]
See https://github.com/celery/celery/issues/3539 for the issue details.

We can _probably_ do away with the sending the broadcast and just reload the database either every message or every couple minutes. That way we only need to have workers subscribe to one queue.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
