### ISSUE TITLE
Users are receiving notifications for repos they've merely forked

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#261]
There are reports of users receiving notifications for packages they don't own or co-maintain, but have simply forked, similar to https://pagure.io/fedora-infrastructure/issue/6445.

This should be investigated since it's likely the new pagure rules causing this.

**Comment by genodeftest** [comment]
I'm affected by this issue. I've forked the https://src.fedoraproject.org/rpms/gnome-session/ and https://src.fedoraproject.org/rpms/gnome-builder repositories to create pull requests. Starting on last saturday morning (UTC), I'm receiving quite many emails for those two packages, although I don't remember changing any email preferences lately.

In the email notification settings, https://apps.fedoraproject.org/notifications/genodeftest.id.fedoraproject.org/email/43896/, only one single item is enabled:
```
A particular user's packages (any acl)

This rule includes messages that relate to packages where the specified user has either commit ACLs or the watchcommits flag.

fasnick
    genodeftest
```

Those emails look like this:

```
From: notifications@fedoraproject.org
To: [censored]
Subject: jkurik commented on RHBZ#1419249 'gnome-session-f[1131]: segfault at 0 ip ...'
Date: Sat, 18 Nov 2017 07:46:39 +0000 (UTC) (18.11.2017 08:46:39)
Precedence: Bulk
Auto-Submitted: auto-generated
X-Fedmsg-Topic: org.fedoraproject.prod.bugzilla.bug.update
X-Fedmsg-Category: bugzilla
X-Fedmsg-Username: jkurik
X-Fedmsg-Package: gnome-session
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
Message-Id: <20171118074639.6571D612E636@bastion01.phx2.fedoraproject.org>

jkurik commented on RHBZ#1419249 'gnome-session-f[1131]: segfault at 0 ip ...'
        https://bugzilla.redhat.com/show_bug.cgi?id=1419249

--
You received this message due to your preference settings at 
https://apps.fedoraproject.org/notifications/genodeftest.id.fedoraproject.org/email/43896
```

**Comment by genodeftest** [comment]
Is this change deployed already or when are the plans to deploy it? I'm asking because I still get those kind of notifications.

**Comment by tmzullinger** [comment]
In case this change is deployed and more data is useful, I can confirm I also received an "ABRT report" for nginx, which I've forked, from notifications@fpo on 12/1.

**Comment by jeremycline** [comment]
It's in staging at the moment, it won't be in production until early next week (likely Tuesday)

**Comment by genodeftest** [comment]
@jeremycline : Thanks for the info!

**Comment by jeremycline** [comment]
Just a heads up, I forgot there was [maintenance scheduled](https://www.fedorastatus.org/q4maint.html) this week for Fedora's infrastructure. A lot of stuff is/will be down so I won't be able to upgrade until _next_ Monday/Tuesday.

On the bright side, since a lot of stuff is down you should get fewer notifications :)
