### ISSUE TITLE
notification culture is unhealthy and spammy, opting people in is wrong and potentially violates the code of conduct

### ISSUE THREAD

**Issue by dpocock** [fedora-infra/fmn#266]
I've noticed that at some point in February 2015 I started receiving notifications by email and IRC whenever I posted a blog.

It is not clear why I need such notifications.  After all, they don't appear to require any action or response.

It feels a lot like being subscribed to a mailing list without my consent, a clear breach of netiquette.

I've also started getting a lot of other notifications, like the new hotness notifications and other things I just don't need or want.  I volunteer to contribute packages, I generally know about the upstream releases through other means (for example, because I am the upstream release manager for several projects), as a volunteer I don't need some script giving me orders.

Even the bugzilla notifications are not really necessary or desirable: I am able to subscribe to all my open bugs using the iCalendar feed so they appear in a prioritized to-do list alongside bugs from upstream projects and other distributions.  Grazing over issues in this way is a lot easier than being bombarded with emails from every direction: usually the bug that generates the most emails is not the most urgent bug to work on.

More recently I started getting notifications about broken dependencies from buildsys@fedoraproject.org: three of those were sent over the weekend for the same project.  How does that help me on a Monday morning to see three notifications for the same thing?  Why can't that system just open a bug, generating a single email and leaving the bug open until the issue is resolved or until I close it?

The Fedora Code of Conduct makes two main points: to [be considerate and be respectful](https://docs.fedoraproject.org/fedora-project/project/code-of-conduct.html).  I feel that this attitude to start sending things to people's email addresses and expecting every developer to individually log in and unsubscribe or customize the notifications falls short of that.  If every organization I ever interacted with did this, my email would be unusable and that is why I feel it falls short of the code of conduct.

As Fedora is a large community I feel it is even more important to set a high standard for the use of communications channels like this and be a good role model for the rest of the free software community.  If every upstream project and distribution did this many volunteers would be pushed away and things would fall apart.

I'd like to request that
a) for any contributors like myself who never opted in to these things and never adjusted the preferences that they should all be disabled again until we choose to subscribe to things individually
b) that policy on the use of email addresses and other contact details (like IRC and XMPP addresses) be revised to prevent any automated notifications in future without an explicit opt-in via the notifications control panel or another mechanism.

**Comment by eseyman** [comment]
> a) for any contributors like myself who never opted in to these things and never adjusted the
> preferences that they should all be disabled again until we choose to subscribe to things individually

I don't like this idea.

As somebody who uses Bugzilla instances deployed by several organisations, I expect:
a) notifications to be activated by default on a reasonable number of  and
b) to be able to configure them to my liking.

Forcing all Fedora contributors to go through their notifications control panel and enable notifications that should reasonably be on by default seems a waste of time and energy (and falls short of the Fedora Code of Conduct for exactly the reasons you mention, imho).

**Comment by dpocock** [comment]
@eseyman the Bugzilla notifications are not part of Fedmsg anyway and although I mentioned them in this bug report, the bug wasn't aimed at them, could you post comments related to Bugzilla in reply to [my email on the devel list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/N6WMBU7DAFC4CDOVHM2Y4OJI3Q7F2KOE/) so this bug report can focus on things that Fedmsg maintainers control?

**Comment by eseyman** [comment]
While I use Bugzilla as an example, I really expect this behaviour across the board. Notifications for reasonably-important events should be on by default and your notifications preferences should be easy to tailor to your liking.

**Comment by dpocock** [comment]
How do you define "reasonably important"?

Have you noticed that what is important for the sender is not always important for the recipient?

Why should all the people who don't think a particular notification is important have to make extra effort to turn things off?

If something really is important shouldn't there be a better way to deal with it than bombarding people with emails?

**Comment by eseyman** [comment]
> How do you define "reasonably important"?

I don't, at least not on my own. I'm guessing consensus is going to be needed on that one.

> Have you noticed that what is important for the sender is not always important for the recipient?

I have no idea how the sender's preferences for receiving notifications factor in on the recipient's.

> Why should all the people who don't think a particular notification is important have to make extra effort to turn things off?

Because if a particular notification is important to a large percentage of people yet disabled by default, the majority of people are going to have to make an extra effort to turn things on, this is a bad experience, especially for newcomers, as well as inconsiderate and disrespectful, a violation of the Fedora Code of Conduct.

> If something really is important shouldn't there be a better way to deal with it than bombarding people with emails?

There are two things here: what chanel you're getting notifications from and the volume of said notifications. On the former, you'll probably never get consensus since it's a very subjective matter. On the latter, I've don't really have an issue one way or another. I don't think I've ever touched my notifications preferences and I get a lot of notifications but they're all stuff that I think is important and that I'm glad I receive so it doesn't qualify as spam in my opinion. Certainly, defaulting to notifications off would make things worse, not better, at least for me.

**Comment by dpocock** [comment]
> >    Why should all the people who don't think a particular notification is important have to make extra effort to turn things off?

> Because if a particular notification is important to a large percentage of people yet disabled by default, the majority of people are going to have to make an extra effort to turn things on, this is a bad experience, especially for newcomers, as well as inconsiderate and disrespectful, a violation of the Fedora Code of Conduct.

Another thing to think about here is impact:
- the impact on somebody who gets too many notifications that they didn't opt-in to may be that they turn off all notifications in every project/site and then they really do miss important things and some people even withdraw from the project completely
- the impact on somebody who has to opt-in is not nearly as severe though, far less people will quit because they didn't get some automated notice from the build system

**Comment by nmav** [comment]
> > Why should all the people who don't think a particular notification is important have to make extra effort to turn things off?
> Because if a particular notification is important to a large percentage of people yet disabled by default, 
> the majority of people are going to have to make an extra effort to turn things on, this is a bad 
> experience, especially for newcomers, as well as inconsiderate and disrespectful, a violation of the 
> Fedora Code of Conduct.

The amount of email I personally receive from fedora infrastructure by default can be hardly classified as important. I would classify it as FYI. Furthermore, the interface to disable receiving messages itself is quite complex, and it is impossible to simply ignore the type of messages that I just received without spending hours understanding how filtering works (and even then I'd have to experiment on whether the filter I just disabled would match the received message, which I have no way to do that).  As such I agree with Daniel's proposal in making fedmsg as conservative as possible. Another work around that could work for me, is making it real easy from opting out from the specific type of messages I just received.

**Comment by jeremycline** [comment]
Hi @dpocock,

Reading the code makes me believe that users aren't being automatically emailed. I think you need to explicitly go into your preferences at https://apps.fedoraproject.org/notifications and press "Enable" (you can also disable notifications there). Perhaps that wasn't always the case, or perhaps I'm missing a path where users have preferences turned on by default. I have no idea what the intended default behavior is, either. Maybe @ralphbean or @pypingou know?

> a) for any contributors like myself who never opted in to these things and never adjusted the preferences that they should all be disabled again until we choose to subscribe to things individually

The problem with this is I don't think we have any way to know who those contributors are.

> b) that policy on the use of email addresses and other contact details (like IRC and XMPP addresses) be revised to prevent any automated notifications in future without an explicit opt-in via the notifications control panel or another mechanism.

I'm certainly okay with this, but it's outside the scope of FMN and not something I have any control over or say in. This is something for FESCo, I think.

**Comment by nirik** [comment]
So, a bit of history here that will hopefully help out with some context: 

When FMN first opened up in production, it replaced a number of other seperate systems that were each sending their own notices in different ways. The idea was that we would stop all those places sending notices and replace it with one place that would send things in a consistent and easily findable manner. 

Most users were not given any notices by default, but we decided to populate users who were in the 'packager' group with a set of notifications that was similar to the notifications they got before from pkgs, koji, etc. Over the years we have added specific new rules to this that we found of use to packagers (for example, taskotron tests) and when someone is added to the packager group they get the default set of rules. 

I think a large number of packagers would find it surprising if they suddenly no longer got notices about commits to their packages or builds or feedback from updates. Note that the broken deps emails you mentioned are in fact something that isn't in FMN and hasnt been centralized yet, it's simply a script that runs after composes.

Perhaps we could send some email or notice when someone is added to packager pointing them to where they could manage their notifications? I really don't think we want to stop providing those rules as new packagers are likely the very people who need them most. You are of course welcome to disagree and ask the council or fesco to rule on the matter.

**Comment by pypingou** [comment]
Adding up to what @nirik just said, before FMN there was no way to configure, customize or even turn off notifications sent from all kinds of application across the entire Fedora infra, koji would send you emails, bodhi as well, pkgdb some others and so on...

When we deployed FMN, we turned off the code for sending those emails in all/most of those apps and made the default for the packager be the same set of notifications as what they would get before.
The difference is that now people can tweak their notifications, specify where they want to receive what (ie: tell me on IRC about a successful koji build and by email about a failed one, so I can go back to it later) or just turn them off either partly or entirely.

The only group that gets notifications by default is the packager group, also because it is the group that got the most notifications before (and I think in general).

While notifications is a sensitive topic that always lead to disagreement (too much vs not enough), do realize that FMN made the situation better, not worst.
And fwiw, I agree with @nirik that we do not want to make packager opt-in.

**Comment by dpocock** [comment]
I agree with the aim of aggregating notifications through FMN, it is commendable.

My concern is about enabling things by default, especially the things like "You just posted a blog" and the duplication of every notice from Bugzilla.

But there is also a cultural issue: as I mentioned in my reply on the thread on devel today, the people in favor of emails are not working that way because it is optimal, they are working that way because it was there by default, they saw other people working that way and they never really thought about it enough to realize how inefficient it is.

Another way to approach this might be telling people that when they join the packager group they have to look at a confirmation page before being accepted in the group.  When they look at the page, there would be a box they can tick or untick for email notifications, another for IRC and there would also be an example of a URL they can use to get the state of their packages as an iCalendar feed.  That could be accompanied by a screenshot of something like Mozilla Lightning's task list so they quickly understand this way of working.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
