### ISSUE TITLE
Email summary should report titles, not full messages

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/fmn#277]
When email digest was made by fmn.consumer it was composed by a short summary with titles and (if verbose=True) full messages, or by just the summary if verbose=False:
```
Digest Summary:
1.  message1 title
2.  message2 title
--------(separator)-------

message1 full description
--------(separator)-------
message2 full description
```

Now the summary is no more a summary:
`message_template = u'{number}.\t{summary} ({ts})\n\t- {link}\n{details}{separator}'`
With verbose=True it simply produces:
```
Digest Summary:
1.  message1 title {timestamp}
{link}
{details}
--------(separator)-------
2.  message2 title {timestamp}
{link}
{details}
--------(separator)-------
```
or with verbose=False:
```
Digest Summary:
1.  message1 title {timestamp}
{link}
--------(separator)-------
2.  message2 title {timestamp}
{link}
--------(separator)-------
```
Would a patch to restore the original behaviour be accepted by admins? Something like:
```
Digest Summary:
1.  message1 title
2.  message2 title
--------(separator)-------

{timestamp} - message1 title
{link}
{details}
--------(separator)-------
{timestamp} - message2 title
{link}
{details}
```

**Comment by jeremycline** [comment]
Hi, thanks for the report.

I would accept such a patch, the change wasn't intentional on my part.

**Comment by mattiaverga** [comment]
Thanks, I will work on it.
I plan to make it works like this with Verbose=True:
```
Digest Summary:
{number}.\t{summary}
--------(separator)-------

{timestamp} - {summary}
{link}
{details}
--------(separator)-------
{timestamp} - {summary}
{link}
{details}
```
With Verbose=False I don't think there's much sense to have a Summary:
```
{timestamp} - {summary}
{link}
--------(separator)-------
{timestamp} - {summary}
{link}
```
If someone has other ideas let me know.
