### ISSUE TITLE
Setting up a development environment with Vagrant fails

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/fmn#279]
I'm following the steps written in https://fmn.readthedocs.io/en/latest/contributing.html to set up a development environment with Vagrant, but the 'vagrant up' command fails:
```
TASK [fmn-dev : Set up the DB user] ********************************************
fatal: [fmn]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.121.254 closed.\r\n", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by jeremycline** [comment]
Hmm. I noticed the example Vagrantfile uses F25 and I neglected to bump it up to F27 which I had in my checkout. Can you try #282?

**Comment by mattiaverga** [comment]
Fix confirmed, thanks!

**Comment by jeremycline** [comment]
Thanks for testing!
