### ISSUE TITLE
Moving from pkgdb to pagure broke package notifications

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#284]
When pkgdb was retired, messages it used to send out are now being sent by pagure at src.fedoraproject.org. For example, when a new package is created, the message topic is now ``org.fedoraproject.{stg,prod}.pagure.project.new`` instead of ``org.fedoraproject.{stg,prod}.pkgdb.package.new``. 

This particular notification was fixed in #290, but there are many other pkgdb notifications that don't map to new messages from pagure. These need to either be re-written to dig into the internals of messages to see if tickets have been filed with particular repos on pagure (it's only a matter of time until those break in some way fmn can't control, though) or retire the notifications.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
