### ISSUE TITLE
[RFE] Please add the date of notification on the notification 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/fmn#285]
I have a suggestion. After some confusions that I have made related with notifications with a big delay .

Please add the date of notification on the notification .

As we expect notifications on time , when don't have it and we receive an notification very delayed , it would help have the date of notification in notification .

**Comment by jeremycline** [comment]
I'm planning on tagging a release next week and letting it sit in staging for a bit. This should be in production soon after that.
