### ISSUE TITLE
State of the android backend?

### ISSUE THREAD

**Issue by recrsn** [fedora-infra/fmn#286]
I noticed that we have an android (GCM) backend. It's probably not being used.

What's the current state of the backend? Can it be lifted so that we can connect some client apps to it?

**Comment by jeremycline** [comment]
I don't know much about the current state, but it probably doesn't work. There's been some refactoring in the backend area and there are no tests for that backend.

@relrod may know more about the history of that backend.

**Comment by recrsn** [comment]
@jeremycline The code looks okay to me, it's using the old GCM API, but it should still work.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
