### ISSUE TITLE
It's not possible to create a new migration without fedmsg-relay installed and configured

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#289]
This is because the migrations start fedmsg at the module-level and don't gracefully handle KeyErrors from the config. It's partially fedmsg's fault for having terrible default configuration behavior, but there's no good reason for the migrations to start ZeroMQ connections at the module level.

The fix is probably to move the ``fedmsg.init`` into the upgrade/downgrade functions for each migration that has it and catching KeyErrors.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
