### ISSUE TITLE
Libravatar is shutting down

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#291]
Libravatar has announced that they are shutting down. FMN uses this to give its users avatars. We should switch to something else, or drop avatars since they don't seem particularly useful in FMN.

**Comment by ferdnyc** [comment]
[Libravatar lives](https://blog.libravatar.org/posts/Brave_new_Libravatar.org/), it seems:

> Almost one year ago (April 2018) Libravatar.org announced it would be going offline forever on the 1st of September 2018. Since then, many things have happened in the background in order to make Libravatar ready for the future and for many more years because we will not go offline. Libravatar is back with completely new software with more features, a new team behind it and running on a new hosting provider. Let's take a look at the details:
> 
> #### Software
> While the old version was based on Python 2 and Django 1.x, the current version is built on top of Python 3 and Django 2.1.x. All pictures are stored in the database instead of the filesystem. This makes it more complicated to run mirrors (currently not possible). The frontend is based on Bootstrap 3 and a customized version of the Tortin theme which can be found on Github. The backend is developed by ofalk and the frontend is developed by nipos. The new software is called "ivatar" and its source code can be found at ofalk's Gitlab instance.
> 
> #### Server infrastructure
> The old server was sponsored by Rackspace and after the shutdown was announced we moved to a temporary virtual server sponsored by Ingo Jürgensmann. Starting on the 19th February with the new software, Libravatar.org has run on Fedora Infrastructure Cloud. They are providing this service for free to us without any expiration date and with as much power as we need. The server administration is done by clime. With the generous sponsorship of Fedora we can continue to provide a stable and reliable service to you.
> 
> #### Domain transfer
> Previously, domains libravatar.org and libravatar.com were registered on personal Francois' account at gandi.net. We have kept the registrar (gandi.net) but transferred the domains to a new libravatar team account. That way, members of the new group can share ownership of the domains. The cost is...wait for it...ZERO € because gandi.net was that generous to sponsor the libravatar domains from up to ground. Thank you gandi.net! You rock!!! And thanks also to tleguern - one of our team members - who communicated it out in French (a real help, since Gandi is also a French company).
> 
> Many thanks to our current and previous sponsors!

(...and so on.) "_Last edited 6 months and 16 days ago_"
