### ISSUE TITLE
Notification timestamp in email header?

### ISSUE THREAD

**Issue by mavit** [fedora-infra/fmn#295]
I notice that notification emails have recently started including a time stamp in the body of the message.  Is there any reason that this information couldn’t be placed in the email’s Date header, so that it could be seen in an email client’s message overview?

I see that [RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.6.1) says the Date field “is specifically not intended to convey the time that the message is actually transported, but rather the time at which the human or other creator of the message has put the message into its final form”, which I think pretty-much covers this case.

I’d be happy to have a go at creating a pull request for this if it seems satisfactory (although I guess I’d need to wait for #294 to land).

**Comment by jeremycline** [comment]
Seems reasonable to me. Since @mattiaverga added the time stamp, it'd be good to hear their thoughts on this change, though.

**Comment by mattiaverga** [comment]
I thought about this when I added the timestamp to the messages.

RFC 2822 says 
> the time at which the human or other creator of the message has put the message into its final form, **ready for transport**

I interpreted this as the time when the email is created by the email() function, opposed to the datetime embedded in the original message which is the time when the original messages has been pushed to fedmsg.
I also thought it was good to have some sort of debug to have the capability to see both times in the email, maybe to check how much time pass from the message to be delivered in fedmsg to the time it is sent by fmn. Ideally, there should be very little difference by the two.

However, I have no objections to modify this behavior if you think it's more reasonable to have it in email headers.

**Comment by mavit** [comment]
> I also thought it was good to have some sort of debug to have the capability to see both times in the email, maybe to check how much time pass from the message to be delivered in fedmsg to the time it is sent by fmn. Ideally, there should be very little difference by the two.

We could put this information in a `Received` header, if we feel it necessary?

**Comment by jeremycline** [comment]
> I interpreted this as the time when the email is created by the email() function, opposed to the datetime embedded in the original message which is the time when the original messages has been pushed to fedmsg.

That's my interpretation as well. I'm traveling so I've not consulted the RFC to see if ``Received`` is the right header to use, but it *sounds* good based on its name. I don't think it wouldn't be that big a deal to have it in both the message body and the headers, too, so this could just be an additive change.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
