### ISSUE TITLE
Minor UI issues with confirming email

### ISSUE THREAD

**Issue by glensc** [fedora-infra/fmn#300]
1. there's no way to re-send confirmation email: https://apps.fedoraproject.org/notifications/glen.id.fedoraproject.org/email/
2. when clicking older confirmation link, i get ugly 404 page
- https://apps.fedoraproject.org/notifications/confirm/accept/16787e7082059004868942844fdb51dc
- gets redirected to https://apps.fedoraproject.org/notifications/confirm/accept/16787e7082059004868942844fdb51dc/
- and is rendered as:
![image](https://user-images.githubusercontent.com/199095/42880103-c10fa8b2-8a9b-11e8-8d6f-94c97292fbfd.png)

3. when clicking already claimed confirmation link, i get 500
- already clamed link https://apps.fedoraproject.org/notifications/confirm/accept/5d94eeef7fe902056d244a368dd74f12
- redirects to https://apps.fedoraproject.org/notifications/confirm/accept/5d94eeef7fe902056d244a368dd74f12/
- and is rendered as 
![image](https://user-images.githubusercontent.com/199095/42880128-dc1ce426-8a9b-11e8-9a00-f7d327e402a1.png)
- @puiterwijk from #fedora-admin said the logs said:
```
15:01:36  puiterwijk> "That value is already claimed."  - so yeah, another bug in handling clicking the link twice
15:01:42  puiterwijk> I think it should just forward you to the homepage
```

ps: sorry for the dark theme in screenshots ;)

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
