### ISSUE TITLE
Jenkins notifications are completely useless

### ISSUE THREAD

**Issue by bochecha** [fedora-infra/fmn#305]
I just received a few emails from notifications@fedoraproject.org about Jenkins:

```
Subject: fedmsg notification

Notification time stamped 1970-01-01 00:00:00 UTC


        https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-build-pipeline-trigger/detail/fedora-build-pipeline-trigger/284568/pipeline/

--
You received this message due to your preference settings at 
https://apps.fedoraproject.org/notifications/bochecha.id.fedoraproject.org/email/58776
```

This tells me absolutely nothing about what happened, and what triggered it.

Given the timing, I assume it is due to some builds I just did in Koji or some updates I sent to Bodhi? The email should say that.

Clicking on the link brings me to a Jenkins page which doesn't help me figure anything about what that is either.

In addition, if I decide not to receive those any more and click the link to the preference settings, I have no idea what negative rule to add. I can chose from:

* Jenkins builds abort
* Jenkins builds starting
* Jenkins builds that become "notbuilt"
* Jenkins builds that fail
* Jenkins builds that finish
* Jenkins builds that finish with warnings

But since neither the email nor the actual Jenkins page told me what the notification was about, then there is no way for me to know which rule the notification is related to.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
