### ISSUE TITLE
Conditional notification rate limits? (vim version overflow!)

### ISSUE THREAD

**Issue by kentfredric** [fedora-infra/fmn#311]
Something that's been bothering me for a while.

I have a notification subscription for "all of Gentoo", however, because "vim" is packaged for Gentoo, and its mapped, and due to `vim` reporting a downright insane number of updates ( literally daily ), "vim" updates account for the gross majority of packages.

https://release-monitoring.org/project/5092/

`vim` may update so often it exceeds release-monitoring's sample rate! 

(these are automated version releases, continuous deployment and soforth )

https://github.com/vim/vim/tags 

Yes, ... hourly versions. This is so much fun -_-

Because every commit is mapped to a version -_-

https://github.com/vim/vim/commits/master

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
