### ISSUE TITLE
please fix the link in email notification

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/fmn#312]
I get [1] when the correct link now is https://src.fedoraproject.org/rpms/pdfbox/commits/master 

[1]
Notification time stamped 2020-08-27 10:39:10 UTC

sergiomb pushed 1 commit to rpms/pdfbox (master)
        https://src.fedoraproject.org/rpms/pdfbox/branch/master

**Comment by sergiomb2** [comment]
link in email notification , gives 404 you need to replace the word "branch" by word "commits" for example: https://src.fedoraproject.org/fork/sergiomb/rpms/opencv/branch/f33 now should be  https://src.fedoraproject.org/fork/sergiomb/rpms/opencv/commits/f33

Thanks

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.

**Comment by sergiomb2** [comment]
this is more or less fixed btw , thanks
