### ISSUE TITLE
Unable to confirm email address second time 😢

### ISSUE THREAD

**Issue by jruzicka-nic** [fedora-infra/fmn#313]
Following steps brought me to a state where I don't get confirmation email for my new email address:

1) add new email address
2) confirm new email address through confirmation email link (so not a mail delivery problem)
3) (accidentally) remove the new address
4) add same new address again

it's now stuck at pending but no confirmation email appears.

Removing and adding the address repeatedly yields no results.

In case it's relevant for debugging, my FAS is `jruzicka`.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
