### ISSUE TITLE
RFE: Add links to RHBZ notifications

### ISSUE THREAD

**Issue by mschwendt** [fedora-infra/fmn#314]
Currently, there are Red Hat Bugzilla ticket related notifications that are inconvenient, because they don't contain a quicklink to the ticket. 

Example:

| Notification time stamped 2020-09-09 09:32:14 UTC
| 
| user@domain updated 'cc' on RHBZ#12345678 'bug subject'

If there were a http://bugzilla.redhat.com/12345678 link, these notifications would become convenient and more helpful.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
