### ISSUE TITLE
Infinite redirection

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fmn#32]
When accessing: https://apps.fedoraproject.org/notifications/login/fedora?next=http://apps.fedoraproject.org/notifications/

Firefox returns me:

```
The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

This problem can sometimes be caused by disabling or refusing to accept cookies.
```

**Comment by ralphbean** [comment]
Where did you get that link?

**Comment by bochecha** [comment]
~~I got it from the FMN emails.~~

That's what you get when trying to log in with FAS in the FMN webapp.

**Comment by ralphbean** [comment]
> That's what you get when trying to log in with FAS in the FMN webapp.

I can't duplicate it.  The login links redirect me to

https://apps.fedoraproject.org/notifications/login/fedora?next=/notifications/home/

which seems to work fine.

Can you confirm that the login link actually points at that different URL in the OP?

**Comment by pypingou** [comment]
I think the problem was somewhat related to the firewall issue we had this week-end. As soon as I saw fedmsg working again, we tried and were able to log-in FMN again.

No idea what the link was/could be, but based on the symptoms, I'd think there is a link.

**Comment by ralphbean** [comment]
OK.  I'm going to close the issue then, since those conditions are both out of our control, and over.
