### ISSUE TITLE
RFE: add mechanism to reclaim IRC nick

### ISSUE THREAD

**Issue by edsantiago** [fedora-infra/fmn#321]
It looks like the fedmsg service has migrated to [Libera](https://libera.chat). I am now receiving a flood of unexpected messages, almost certainly because my Libera nick (esm) != my Freenode one (edsantiago). I would like to claim the `esm` nick, but when I try, fedmsg gripes with a JSONy `reason": "That value is already claimed."`.

Suggestion 1 (easy): when transferring to new IRC provider, wipe all existing nick mappings.

Suggestion 2 (harder): don't reject attempts to add a nick, just go through the verification mechanism. If I can verify my nick, you should add it to my FAS account, and remove that mapping from whoever currently has it.

Suggestion 3 (probably even harder): allow mappings for multiple IRC networks.

**Comment by edsantiago** [comment]
ping, what is the status of this?

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
