### ISSUE TITLE
Migrate to different CI

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/fmn#326]
The current travis-ci is not working. It needs to be replaced by something else. Like for some other projects like [Anitya](https://github.com/fedora-infra/anitya) or [the-new-hotness](https://github.com/fedora-infra/the-new-hotness) I would like to use Zuul CI for this project.

**Comment by ekohl** [comment]
With https://github.com/fedora-infra/fmn/commit/03397b4d578c7ab2a9c87dbedd51e3a8d6b85ebb, can this be closed?

**Comment by Zlopez** [comment]
The zuul CI doesn't working yet, I created an [issue](https://pagure.io/fedora-ci/general/issue/304) for it on the official tracker.

**Comment by Zlopez** [comment]
The zuul migration is now done
