### ISSUE TITLE
migrate to OIDC for logging in

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/fmn#329]
Currently FMN uses OpenID via ipsilon to allow users to log into the web interface.

This should be migrated to OpenID Connect (OIDC)

**Comment by Zlopez** [comment]
Will using fasjson_client library help with this issue? Could fixing https://pagure.io/fedora-infrastructure/issue/9746 also solve this issue?

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
