### ISSUE TITLE
Failed anitya notifications

### ISSUE THREAD

**Issue by brianjmurrell** [fedora-infra/fmn#336]
I have the following notification configured at https://apps.fedoraproject.org/notifications/brianjmurrell.id.fedoraproject.org/email/68769/

![image](https://user-images.githubusercontent.com/559317/152592933-ffb8006b-c3c1-4655-a5b6-5593789d6254.png)

I did not get any notifications for either of the releases in the red box:

![image](https://user-images.githubusercontent.com/559317/152592845-2b355ae6-b4dd-4b72-ab20-bb4f765ab55b.png)

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
