### ISSUE TITLE
 As a fedora-infra member, I want to have fmn's packaging automated.

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/fmn#344]
## Acceptance Criteria

* packit.yml is added to the project
* once added, we can successfully create released rpms for fmn
* https://src.fedoraproject.org/rpms/python-fmn is un-dead and updated by packit

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
