### ISSUE TITLE
Add an rss backend

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn#37]
FMN doesn't have rss yet, just irc and email.

Someone in #epel was asking how to watch specific packages for updates via rss.

Could see it as useful for folks that just care about a few things.

**Comment by ralphbean** [comment]
We could generate it the same way we do the datagrepper preview on the filter page.. but just cache the results in memcached so that we don't hammer datanommer too hard.

**Comment by tvvocold** [comment]
+1

**Comment by remicollet** [comment]
+1

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
