### ISSUE TITLE
Email parser is broken

### ISSUE THREAD

**Issue by RichiH** [fedora-infra/fmn#39]
I tried adding a valid address on https://apps.fedoraproject.org/notifications/richih.id.fedoraproject.org/email/ following the scheme `foo+fedora.org@bar.baz` which got rejected with https://apps.fedoraproject.org/notifications/api/details displaying

`{
  "reason": "value must be an email address"
}`

I rely on `+foo` to filter my mail, so this is a bit of a bummer.

Thanks,
Richard

**Comment by ralphbean** [comment]
> so this is a bit of a bummer

Agreed.  Will try to get it fixed for the next release.  Thanks!

**Comment by RichiH** [comment]
Great, thanks! Is there a rough ETA?

**Comment by ralphbean** [comment]
> Is there a rough ETA?

I'm just back from vacation and trying to sketch out goals and timelines.  I'll promise March 1st and see where that gets me.. ;)  There's just a few other projects to wrap up first.  Thanks for your patience.
