### ISSUE TITLE
Filters from orther than Generic Rules does not show edit field

### ISSUE THREAD

**Issue by voxik** [fedora-infra/fmn#40]
I am trying to add "Particular Koschei package groups" filter and it seems there should be possible to edit the groups. At least the description states "You can specify more groups separated by commas." However, there is no edit field to list the groups.

It seems that the edit fields are available just for the "Generic Rules" but unavailable for others. Or am I missing something? Should I combine the filters somehow?

**Comment by ralphbean** [comment]
Thanks for the report @voxik, I totally missed this.

fedora-infra/fmn.lib#28 should fix it.

**Comment by voxik** [comment]
Thanks for the fix. Please let me know when it will be available for testing.

**Comment by ralphbean** [comment]
Should be today or tomorrow.

**Comment by ralphbean** [comment]
@voxik it should be live now if you're available to test it.

**Comment by voxik** [comment]
It shows the edit field in the rule list on the right side, but there is still no edit field when the rule is in use in the filter.

**Comment by ralphbean** [comment]
> It shows the edit field in the rule list on the right side, but there is still no edit field when the rule is in use in the filter.

Oh, that's a general problem with all of the rules.  Could you file a separate RFE issue for that?
