### ISSUE TITLE
Export filters

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fmn#42]
It would be pretty nice to have a way/format (json?) to export a set-up of filters and rules.

This way we could do something like:
- I am not receiving emails which I thought I should
- goto FMN
- find instruction on how to tests filters
- download my set-up
- call `fmn-cli --debug <filters> <fedmsg-id>`
- See which filters selects/blocks

**Comment by ralphbean** [comment]
Nice thing -> there's already an internal json representation of filters and rules, used to cache them in the backend.  We just have to export it.

We can use the same `fmn.lib` message-matching code in the cli that the real backend uses.

**Comment by ralphbean** [comment]
Closed with #41.
