### ISSUE TITLE
Don't send notifications about pkgdb2branch by default

### ISSUE THREAD

**Issue by bochecha** [fedora-infra/fmn#45]
I received this email:

```
run of pkgdb2branch started by limb completed


--
You received this message due to your preference settings at
https://apps.fedoraproject.org/notifications//bochecha.id.fedoraproject.org/email/20530
```

The filter setting this is about is pretty much the default for packages I maintain.

I think this corresponds to when limb handled the cvsadmin request for some gnome-\* package, adding acls for it to `group::gnome-sig` (of which I am a member)

However, that's hard to tell, since the message doesn't really contain any useful detail.

In any case, given that I already receive notifications for having gotten the acls on the new package, maybe this isn't very interesting to have in the default filters?

**Comment by ralphbean** [comment]
> I think this corresponds to when limb handled the cvsadmin request for some gnome-\* package, adding acls for it to group::gnome-sig (of which I am a member)

I think that's the correct assessment also.
