### ISSUE TITLE
Could it sending meeting minutes automatically to mailinglist?

### ISSUE THREAD

**Issue by tvvocold** [fedora-infra/fmn#48]
In https://apps.fedoraproject.org/notifications/myid.id.fedoraproject.org/email/  : 
My active filter is "All messages matching a regular expression" &" A particular user's packages" and "All IRC meeting events" , and i test it in #fedora-zh, but couldn't get email when i #endmeeting.
(I can forward the noti-email to mailling list by add a filter in Gmail)
Why and how to fix?

**Comment by tvvocold** [comment]
@ralphbean

**Comment by ralphbean** [comment]
Hi @tvvocold.  The issue I think is that, for a message to be delivered it must match **all** rules on the filter and there's _no way_ as far as I know to have a message that is _both_ about an irc meeting _and_ about a package.  (Packages are not inherently part of irc meeting events).

In order to advise further, I'll need to know what your regular expression is for.  Can you explain it?

Ultimately, you're probably going to have to make a few separate filters:
- One for "messages about your packages"
- One for IRC meetings (perhaps that also match a certain regex).
- Another for...?

Let me know what the regex is for and maybe we can figure out something more conclusive.

**Comment by tvvocold** [comment]
Hi @ralphbean Thx for answer.
and here is my filter:
(as u can see,i had disable the packages and other filters,what i  need is that fedora-app-noti-email send me mails with the irc meeting minutes so that  i can  forward it to mailing list (by add a filer in gmail), What should i do next?) Thx!
![image](https://cloud.githubusercontent.com/assets/4530539/6129263/eab6dff6-b177-11e4-8989-77294372108f.png)

FYI: Till now(i test it by startmeeting and endmeeting in fedora-zh) i could not got the noti-mails.

**Comment by ralphbean** [comment]
You have to re-enable that 'github' filter with the 'All IRC meeting events' filter.  That should send emails about _all_ irc meetings to you.  But that's not quite what you want.

I would edit that filter, delete the 'All IRC meeting events' rule, and add a new rule just for the _end_ of meetings, (when the minutes are available).

I'd then add a second rule to the filter with a regex looking for `(fedora-zh)` so that you only get messages about fedora-zh meetings (and not all the other meetings that go on).

**Comment by ralphbean** [comment]
I'm going to close this for now.  Please re-open if you have problems with it.

**Comment by tvvocold** [comment]
Well, i do not think that would work, i need a automatically server for send meeting minutes to mailing list, so could u modefi the irc fliter to send ALL meeting logs to mail?
BTW, it seems the All irc meeting event" rule does't work very well (or server doesn't work very well) (i only got 1-2 mails about whatever meetings in 1-2 weeks till now)

**Comment by ralphbean** [comment]
> could u modefi the irc fliter to send ALL meeting logs to mail?

Yes, you could have it do that by just using the 'All irc events' rule.

> it seems the All irc meeting event" rule does't work very well (or server doesn't work very well) (i only got 1-2 mails about whatever meetings in 1-2 weeks till now

But, (this is based on your screenshot), you had it disabled.  It shouldn't have sent any in that case.

**Comment by tvvocold** [comment]
in fact i enable it , and u can try it in that sites. see if u can got meeting mails.(with all meeting logs)

**Comment by ralphbean** [comment]
> with all meeting logs

Heh, this part will be working soon.  The code is here, https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/commit/7baa7c9fdcdc3093596496a60d354ef96071ac49  -- it just needs to be deployed to the server still.  Hopefully today.

**Comment by tvvocold** [comment]
Nice! that would be wonderful! Thx!
BTW, plz fix the server too, seems like it did't work very well(Maybe the gmail somehow block some mails from server?)

**Comment by tvvocold** [comment]
@ralphbean Hi,sry to bother u , but is this thing( to send meeting minutes automatically to mailinglist)  working now in https://apps.fedoraproject.org/notifications?

**Comment by ralphbean** [comment]
@tvvocold should be, yes.  What are you seeing?

**Comment by tvvocold** [comment]
i cannot find that... it seems the All irc meeting event" rule isn't what i need.

**Comment by tvvocold** [comment]
@ralphbean Can u reopen this issue Since there is NO sending meeting minutes to maillist feature.
What i got is

```
Mailing list emails
Including this rule will trigger a notification anytime an email is POSTED to any Fedora Project mailman3 list.
```

but what i am looking for is sending meeting minutes like （#fedora-admin) to maillist

**Comment by ralphbean** [comment]
Sure.  Will re-open it.  Again I'm fairly sure that it can be done with the present pieces.  Will have to verify and get back to you.

**Comment by ralphbean** [comment]
@tvvocold btw, we got this working for sending emails to the meetingminutes list in #72.

**Comment by ralphbean** [comment]
The configuration looks like this:

![fmn-meeting-minutes](https://cloud.githubusercontent.com/assets/331338/6790263/cf2cbe48-d17c-11e4-8656-c0e0fe5f85c0.png)

**Comment by tvvocold** [comment]
Cool! but just one rule? 
how can i specify a irc channel like #fedora-zh?
And i need to use list mail to sign up tha FAS?

**Comment by ralphbean** [comment]
> Cool! but just one rule?

Yeah!  In this case, we want to forward all meetings in all channels to the meetingminutes list, so just one rule is needed.

> how can i specify a irc channel like #fedora-zh?

You would combine that one rule with a second rule for 'All messages matching a regular expression'.  You could just put `fedora-zh` in for the pattern there.

> And i need to use list mail to sign up tha FAS?

This was the trickiest part.  You would need to put the mailing list address into FMN, yes, and then confirm the subscription.

**Comment by tvvocold** [comment]
So i add a second rule for 'All messages matching a regular expression' and i got 3 noti-emails when i endmeeting:

```
1, tvvocold started a meeting in #fedora-zh
2, tvvocold raised a point of information in a meeting in #fedora-zh: "Just a test."
3, Meeting started by tvvocold at 01:33:18 UTC. The full logs are available
```

but i just need the third mail.

Update: Now i got  a new mail:

```
tvvocold commented on issue #48 on fedora-infra/fmn
```

Anyidea?

**Comment by ralphbean** [comment]
Sounds like you added two _filters_ each with one _rule_.  I think you need _one_ filter with _two_ rules attached to it.

**Comment by tvvocold** [comment]
OK, cool.
I think that would be even cooler if it work with [IFTTT](http://ifttt.com)

**Comment by ralphbean** [comment]
If the fmn site allowed you to create custom RSS feeds, that would do it, right?  (the issue for that is #37).

**Comment by tvvocold** [comment]
I mean by use ifttt, we can push the noti-msg to phone or something else.(not just emails or irc). That's even cool!
FYI: There is a [wheel for create custom RSS feeds](http://feed43.com).

**Comment by pypingou** [comment]
Is feed43 FOSS?
