### ISSUE TITLE
"Searching for example messages that match this filter" doesn't seem to work

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#50]
I have never seen any samples at all under the "Searching for example messages that match this filter" header. Even when I receive a message triggered by a particular filter, and then open up that filter in a web browser, the "example messages" section is still empty.

**Comment by ralphbean** [comment]
This is an artifact of just how slow the datagrepper database has become.  It is very slowly searching for examples.  If you waited "forever" you'd eventually see some.

This counts as a bug.  We need to put effort into speeding up our queries to that database.

**Comment by ralphbean** [comment]
> We need to put effort into speeding up our queries to that database.

This is fixed now.  :)
- http://threebean.org/blog/revisiting-datagrepper-performance/
- https://twitter.com/ralphbean/status/577588424737210370
