### ISSUE TITLE
Link to event that triggered a notification

### ISSUE THREAD

**Issue by tyll** [fedora-infra/fmn#53]
Notifications like

{{{
kevin updated a ticket on the Fedora Infrastructure trac instance
        https://fedorahosted.org/fedora-infrastructure/ticket/4670
}}}

do not really help to figure out what happened, because they do not contain any information about what was changed. I believe in this case kevin added comment 7. To make it easier for all events to figure out what happened, a link to the event in datagrepper would help.

**Comment by pypingou** [comment]
Was this by email or irc?

(as in irc as a `triggered by https://apps.fedoraproject.org/notifications/user.id.fedoraproject.org/irc/XXX`)

**Comment by tyll** [comment]
On Thu, Feb 19, 2015 at 12:30:35PM -0800, Pierre-Yves Chibon wrote:

> Was this by email or irc?
> 
> (as in irc as a `triggered by https://apps.fedoraproject.org/notifications/user.id.fedoraproject.org/irc/XXX`)

email

**Comment by pypingou** [comment]
We have a bit more space in email so I guess we could include the filter as well as the fedmsg message that started the chain

**Comment by tyll** [comment]
the filter is already added there, however the notification does not really tell me what happened with the ticket. E.g. I got the ticket after I already responded to the comment kevin made, which first confused me, because I thought it was about a notification that kevin responded again.

**Comment by ralphbean** [comment]
Here's the message in question:  https://apps.fedoraproject.org/datagrepper/id?id=2015-e059af4c-b3b9-4c5e-a02d-0876329aa2de&is_raw=true&size=extra-large

**Comment by ralphbean** [comment]
Unfortunately, I don't see an obvious way to get the direct link to the comment from trac's plugin interface.  Here's the place in our fedmsg plugin that would need to be changed to publish that kind of information:  https://github.com/fedora-infra/trac-fedmsg-plugin/blob/develop/trac_fedmsg_plugin.py#L104-L122

That said, we _can_ easily include the text of the comment in the email, which should make it a little more obvious to recipients.

**Comment by ralphbean** [comment]
> That said, we can easily include the text of the comment in the email, which should make it a little more obvious to recipients.

And this is actually already done as of fedora-infra/fedmsg_meta_fedora_infrastructure#211, so I'm going to close this one.
