### ISSUE TITLE
Add a more detailed koji build completed filter

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fmn#54]
The old koji mails sent something like: 

Package: ansible-1.8.3-1.el7
Tag: epel7-testing-candidate
Status: complete
Built by: kevin
ID: 612324
Started: Tue, 17 Feb 2015 23:39:49 UTC
Finished: Tue, 17 Feb 2015 23:41:56 UTC
Changelog:
- Tue Feb 17 2015 Kevin Fenzi kevin@scrye.com 1.8.3-1
- Update to 1.8.3
- Sun Jan 11 2015 Toshio Kuratomi toshio@fedoraproject.org - 1.8.2-3
- Work around a bug in python2.6 by using simplejson (applies in EPEL6)
- Wed Dec 17 2014 Michael Scherer misc@zarb.org 1.8.2-2
- precreate /etc/ansible/roles and /usr/share/ansible_plugins

SRPMS:
  ansible-1.8.3-1.el7.src.rpm
## Closed tasks:

Task 8973189 on buildhw-04.phx2.fedoraproject.org
Task Type: buildArch (ansible-1.8.3-1.el7.src.rpm, noarch)
logs:
  http://koji.fedoraproject.org/koji/getfile?taskID=8973189&name=build.log
  http://koji.fedoraproject.org/koji/getfile?taskID=8973189&name=mock_output.log
  http://koji.fedoraproject.org/koji/getfile?taskID=8973189&name=root.log
  http://koji.fedoraproject.org/koji/getfile?taskID=8973189&name=state.log
rpms:
 http://kojipkgs.fedoraproject.org//packages/ansible/1.8.3/1.el7/noarch/ansible-1.8.3-1.el7.noarch.rpm

Task 8973158 on buildhw-11.phx2.fedoraproject.org
Task Type: buildSRPMFromSCM (/ansible:7c6e5edbc6bdbd2d30e159e2923d1ba617e58a44)
logs:
  http://koji.fedoraproject.org/koji/getfile?taskID=8973158&name=build.log
  http://koji.fedoraproject.org/koji/getfile?taskID=8973158&name=checkout.log
  http://koji.fedoraproject.org/koji/getfile?taskID=8973158&name=mock_output.log
  http://koji.fedoraproject.org/koji/getfile?taskID=8973158&name=root.log
  http://koji.fedoraproject.org/koji/getfile?taskID=8973158&name=state.log

Task 8973199 on arm02-builder15.arm.fedoraproject.org
Task Type: tagBuild (noarch)

The new build completed just gives a link to the build. 
Might be nice to have a 'detailed build complete' filter if possible?

**Comment by ralphbean** [comment]
Totally possible.  There's a little API designed to be filled out with stuff like this.

Thanks for filing!

**Comment by robert-scheck** [comment]
It would be also great if the subject could get more verbose again (mention the tag):

Old: `Package: phpMyAdmin-4.3.10-1.fc20 Tag: f20-updates-candiate Status: complete Built by: robert`
New: `robert's phpMyAdmin-4.3.10-1.fc20 completed`

**Comment by robert-scheck** [comment]
I am sorry, this is not really solved:

```
robert's php53-tcpdf-6.2.4-1.el5 completed

Package:    php53-tcpdf-6.2.4-1.el5
Status:     complete
Built by:   robert
ID:         616079
Started:    Fri, 27 Feb 2015 21:26:44 UTC
Finished:   Fri, 27 Feb 2015 21:28:17 UTC

Closed tasks:
-------------
Task 9095043 on buildvm-13.phx2.fedoraproject.org
Task Type: build (noarch)
Link: https://koji.fedoraproject.org/koji/taskinfo?taskID=9095043

Task 9095043 is not finished

        http://koji.fedoraproject.org/koji/buildinfo?buildID=616079
```

I would love to see all the other direct links and information again...

**Comment by ralphbean** [comment]
What links are you talking about?

**Comment by ralphbean** [comment]
Wait.  Something is wrong here.  The top portions say that the build is completed.  But the tasks say that the task is not yet closed.  That.. is wrong, you're right.

**Comment by ralphbean** [comment]
@robert-scheck can you give us the headers for that email?  Specifically, when was it sent?

**Comment by robert-scheck** [comment]
```
Date: Fri, 27 Feb 2015 21:29:41 +0000 (UTC)
```

and

```
Received: by bastion01.phx2.fedoraproject.org (Postfix)
        id 4CC74604CD8A; Fri, 27 Feb 2015 21:29:41 +0000 (UTC)
Delivered-To: robert@fedoraproject.org
Received: from notifs-backend01.phx2.fedoraproject.org (notifs-backend01.phx2.fedoraproject.org [10.5.126.168])
        by bastion01.phx2.fedoraproject.org (Postfix) with ESMTP id 423D7604CD79
        for <robert@fedoraproject.org>; Fri, 27 Feb 2015 21:29:41 +0000 (UTC)
```

**Comment by ralphbean** [comment]
@robert-scheck, I'm pretty sure this is the result of a race-condition between FMN and koji.  The code in fedora-infra/fedmsg_meta_fedora_infrastructure#214 should fix it.

**Comment by robert-scheck** [comment]
@ralphbean, I don't think this has been really solved so far when seeing this a few minutes ago:

```
Package:    phpMyAdmin-4.3.12-1.fc23
Status:     complete
Built by:   robert
ID:         620363
Started:    Sat, 14 Mar 2015 17:09:39 UTC
Finished:   Sat, 14 Mar 2015 17:11:03 UTC

Closed tasks:
-------------
Task 9233490 on buildvm-14.phx2.fedoraproject.org
Task Type: build (noarch)
Link: https://koji.fedoraproject.org/koji/taskinfo?taskID=9233490

Task 9233490 is not finished

        http://koji.fedoraproject.org/koji/buildinfo?buildID=620363
```

**Comment by ralphbean** [comment]
Ah, the code-change hasn't yet been released or deployed.
