### ISSUE TITLE
Add less detailed git commit filter

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fmn#55]
The current dist git comment includes a diff. It might be nice to have a filter that just gives a link to the commit without the diff.

**Comment by robert-scheck** [comment]
It also would be a better default if not both (git and fmn) are sending a notification by default. So if you just enable e-mail communication, you receive two e-mails for each commit or merge.

**Comment by ralphbean** [comment]
@pypingou, @bochecha - can we turn off email from gitolite3 before freeze sets in on Tuesday?  Or is that too rushed.

**Comment by ralphbean** [comment]
To disable dist-git emails we need to make sure and add a scm-commits FAS user who gets them still for the scm-commits list

Messages for commits, pkgdb changes, and lookaside uploads.

https://lists.fedoraproject.org/pipermail/scm-commits/Week-of-Mon-20150216/thread.html

**Comment by robert-scheck** [comment]
FMN also sends always the full diff (after e.g. `git merge origin/master`) even if the Git e-mail just tells that the diff has been already sent in a separate e-mail.

**Comment by pypingou** [comment]
I think it's a git hook sending the email, so it should be fairly simple to drop it

**Comment by bochecha** [comment]
Yeah, it's the gnome-post-receive-send-email commit hook (not sure the exact name, but it's definitely 'post-receive' and it's based on the original GNOME one)

**Comment by ralphbean** [comment]
So, we need a way for the git hook that sends fedmsg messages originally to detect if the commit already exists in another branch, and if so.. just mark that somehow in the message.

Later, when the message is received, we can look for that flag in the message and only return a small amount of text in the long_form routine.

**Comment by ralphbean** [comment]
> we need a way for the git hook that sends fedmsg messages originally to detect if the commit already exists in another branch, and if so.. just mark that somehow in the message.

This is done now with the `seen` field in the `git.receive` messages now.

> we can look for that flag in the message and only return a small amount of text in the long_form routine.

This is done now (and deployed) as of fedora-infra/fedmsg_meta_fedora_infrastructure#233

**Comment by ralphbean** [comment]
OK, old email mechanisms are now turned off.  FMN is sending pkgdb, git, and lookaside messages to the scm-commits list.
