### ISSUE TITLE
Formatting of IRC notification messages

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#56]
It would be great if the formatting of IRC notification messages would be possible, because "buildsys.build.state.change -- robert's phpMyAdmin-4.3.10-1.fc20 started building http://koji.fedoraproject.org/koji/buildinfo?buildID=613539" (maybe even with the reason link afterwards) reduces the readability for me. Instead I would like to have no prefix (buildsys.build.state.change) simply because "started building" already indicates that it is somehow a buildsys build state change.

**Comment by ralphbean** [comment]
Agreed!  That's `buildsys.build.state.change` thing is a fragment of the fedmsg topic for that message.. but there's really no need to surface that to users.  It's helpful to me to quickly distinguish between events, but that's the odd case, I think.
