### ISSUE TITLE
Add an XMPP backend

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#57]
FMN doesn't have XMPP (Jabber) yet, just IRC and e-mail.

**Comment by ralphbean** [comment]
Do you have any ideas about how this should work?  I don't use jabber for anything directly, so I could use some education.

Would you need to put in your contact value in the form `server:port/nickname` or something like that?

**Comment by robert-scheck** [comment]
Imagine XMPP like SMTP. An XMPP account on e.g. an existing XMPP server would be needed (similar like for the IRC bot or for e-mail), the recipient would be the JID (Jabber ID), e.g. `localpart@jabberserver.tld`. There are tools like `sendxmpp` (please do not use that one, I do not think that one is really great) which could do the job simply.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
