### ISSUE TITLE
SPIKE: Database Structure

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/fmn#573]
# Story

As a backend developer working on FMN,
I want to know how to store what information in the database,
so it can be easily, efficiently and reliably stored and used.

# Acceptance Criteria

- [x] What needs to be stored in the DB regarding rules, notification targets etc. is discussed in the team and documented:
  - [x] Entities that should be accessible as bona fide ORM objects (DB tables) are identified.
  - [x] How entities relate to one another is known.
  - [x] Information that doesn’t have to be directly efficiently selectable is identified.

NB: this doesn't need to be hammered out in detail, but we want a rough sketch at least.

# Background

Idea: We only need to be able to query rules efficiently (in the consumer) by their inputs – for example message topic, user or group involved in a message being processed. What should be done with them further could e.g. be stored as a single JSON field in the row, which would let us get away without having to reflect all corner cases there in the DB structure (say, as a set of mutually exclusive columns or complicated “rule bits” like interconnected nodes of a decision tree). This would make the database structure a good deal simpler. Cf. the general purpose `data` field in [`Node`](https://github.com/CentOS/duffy/blob/542b3ed3207de8b0beb640f6342912bda8278222/duffy/database/model/node.py#L54) and other ORM classes in Duffy. 

One result of the discussion should be whether or not this assumption holds true.

**Comment by james02135** [comment]
All tasks completed with commit [#577](https://github.com/fedora-infra/fmn/commit/8f0e0d9d59d7698f8c3ab961e233098f1d595dc7)
Single JSON field covered by "params" field in tracking_rule model
