### ISSUE TITLE
Implement DB Structure

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/fmn#574]
# Story

As an FMN backend developer,
I want ORM model classes to exist which map the identified database structure,
So I can implement functionality that builds upon them.

# Acceptance Criteria

- [x] For each of the entities identified in #573, an ORM class exists mapping the entity with its identified properties and relationships to other ORM classes, where applicable, exists.
  - [x] destination.py
  - [x] filter.py
  - [x] generation_rule.py
  - [x] rule.py
  - [x] tracking_rule.py
  - [x] user.py

**Comment by james02135** [comment]
Completed with commit [#577](https://github.com/fedora-infra/fmn/commit/8f0e0d9d59d7698f8c3ab961e233098f1d595dc7)
