### ISSUE TITLE
Website link is wrong?

### ISSUE THREAD

**Issue by remyabel2** [fedora-infra/fmn#581]
On https://apps.fedoraproject.org/notifications/username.id.fedoraproject.org/email/ there are links to https://fedmsg.com/, but this appears to be a Python learning site that has no connection to the Fedora messaging bus.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
