### ISSUE TITLE
Preview the generated notifications

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fmn#604]
Message preview/forecasting (API) using frontend they query API they can be told how many notifications they will be sent using that particular rule so they can decide what kind of filtering they will need, eg will they need more to get less notifications or less to get more.

**Comment by amoloney1** [comment]
Message preview/forecasting (API) using frontend they query API they can be told how many notifications they will be sent using that particular rule so they can decide what kind of filtering they will need, eg will they need more to get less notifications or less to get more.
