### ISSUE TITLE
Uploading source to lookaside cache causes two mails

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#61]
Uploading source to lookaside cache causes two mails: Old "File v1.0.0.tar.gz uploaded to lookaside cache by robert" and new "robert uploaded v1.0.0.tar.gz for librsync" - guess this should be reduced to one e-mail by fmn? And unfortunately the new e-mail does not include the relevant line of `sources`, e.g.

```
829fad850e470dab9cc38a955746aa72  v1.0.0.tar.gz
```

**Comment by ralphbean** [comment]
TODO:
- [x] Add a long_form implementation for lookaside.new messages with this info
- [x] Disable the old emails from lookaside.

**Comment by pypingou** [comment]
https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/pull/209 should take care of the first item

**Comment by ralphbean** [comment]
This is done now.  Old emails disabled.
