### ISSUE TITLE
Community Blog Post #1

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/fmn#636]
# Story

As a community member,
I want that the project progress is communicated by the people involved,
so I know where things are heading and how they affect me.

# Acceptance Criteria

- [x] A community blog post exists which …
  - [x] … describes why we reimplement FMN (problems, missing functionality, etc.) …
  - [x] … and tells people where we are right now.
- [x] A new card like this exists for a followup blog post in a month or so.

# Background

Doesn’t have to be long. We sent out an email to the community earlier (see [hackmd doc](https://hackmd.io/1M2OQ4QfS52bNYZOoda0gQ)) which contains some of this information.

**Comment by james02135** [comment]
Hackmd [doc](https://hackmd.io/@jamricha/ByeT9nLrj/edit) in progress

**Comment by james02135** [comment]
https://communityblog.fedoraproject.org/?p=11608&preview_id=11608&preview_nonce=b9bcb66de1&preview=true

Sent in for review, should be published shortly
