### ISSUE TITLE
Defaults are a bit too much for anitya

### ISSUE THREAD

**Issue by bochecha** [fedora-infra/fmn#64]
Anitya is awesome, and so is fedmsg/FMN.

However, the three together are also a bit spammy.

This morning, I woke up to the following emails:
- A new version of "libhtp" has been detected: "0.5.17" in advance of "0.5.16"
- the-new-hotness filed a bug on libhtp
- [Bug 1196179] New: libhtp-0.5.17 is available
- [Bug 1196179] libhtp-0.5.17 is available

That's a bit much. :smile: 

The first two should just not be sent. I'm getting an email from Bugzilla for the bug anyway, so why send me an email that someone has opened a bug, and that a new version was found?

**Comment by ralphbean** [comment]
Agreed!  @tyll suggested that we can set a flag on python-bugzilla so that the bz bugs don't send emails initially.  A patch with that would have to be added to the-new-hotness.

**Comment by bochecha** [comment]
> so that the bz bugs don't send emails initially.

You mean the last two in the list above?

Those are the ones I would have thought we would want to keep actually, as they have the most information. :confused:

**Comment by bochecha** [comment]
And a new one today:
- the-new-hotness saw an update for dbus, but pkgdb says the package owner is not interested in bugs being filed

Surely, if the owner is not interested in bugs being filed, they also don't want an email telling them that? :smile: 

Honestly, I think we could just completely drop the anitya notifications by default, and only keep the notifications coming from Bugzilla for the bug creation.

**Comment by bochecha** [comment]
A new one today:
- A new version of "ibus-cangjie" has been detected:  "v2.3" in advance of "v2.2"

Then, the-new-hotness proceeded to NOT create a bug report, I supposed because I had already built that new ibus-cangjie in Rawhide, F22 and F21.

So if the-new-hotness was smart enough to not do anything, perhaps I shouldn't have received the anitya notification either?

I'm really starting to think we shouldn't receive anitya notifications by default. At all.

If monitoring is enabled, then the-new-hotness will pick up on that, and do its job (and it does it very well from what I can see :+1:) and decide whether the maintainer needs to be notified or not. And if monitoring is disabled, then the maintainer doesn't want to hear about it (that's the previous comment).

Does that sound crazy, or would you accept a patch to the FMN email defaults that would completely ignore the anitya notifications?

**Comment by ralphbean** [comment]
@bochecha, this sounds good.

What do you think about going a step further and adding an alembic upgrade script that will trawl through the database and modify people's existing filters?

**Comment by bochecha** [comment]
Migrating existing configurations sounds good, but it's more work than I have time for right now unfortunately. :disappointed:

**Comment by ralphbean** [comment]
Going to call this closed now that the defaults are updated.  Thanks @bochecha!

**Comment by bochecha** [comment]
One thing I hadn't taken care of in my pull-request was messages like this:

> the-new-hotness saw an update for atk, but pkgdb says the package owner is not interested in bugs being filed

These really should be ignored by default as well. :disappointed:

**Comment by bochecha** [comment]
I can't figure out what to put in `fmn/lib/defaults.py` for this, though. :confused:

**Comment by QuLogic** [comment]
I hit Reset on my filters so they're all the defaults (they were previously however I set them up before becoming a packager), and now I'm getting anitya and the-new-hotness messages that I never received before, even though it says here that the defaults should have them disabled.

I manually added a negative "All release-monitoring.org events" rule to the "Events on packages that I own" filter, but I still get the-new-hotness messages.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
