### ISSUE TITLE
IRC notification to a channel (instead of a user)

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/fmn#66]
Hi,

It will be nice to allow notification to a specific IRC channel, instead of a private user message.

Example: see the github IRC service hook.

Usage: for people having a dedicated IRC channel (ex #remirepo in my case)

Of course, notification to some high traffic channel should be discouraged (even forbidden, ex #fedora-devel)

**Comment by pypingou** [comment]
We originally thought about this but it can lead to some spamming problem if it is allowed to go to any chan.

I think the idea was to offer an irc bot or help on how to setup one to those wanted this service.

**Comment by remicollet** [comment]
If the bot send "notices" without joining the channel (lowest noise level), the "mode -n" need to be set, this should protect most channel from unwanted flood.

For freenode 

```
/msg ChanServ set #CHANNELNAME mlock -n
```

For others

```
/mode #CHANNELNAME -n
```

**Comment by ralphbean** [comment]
@remicollet we already have a different mechanism for this and we have bots doing this in #fedora-ask, #fedora-releng #fedora-design #fedora-latam and others.

What kind of messages would you like in #remirepo?  If the existing mechanism is unable to do what you want, we can look at adding something more sophisticated like this to FMN.

**Comment by ralphbean** [comment]
Ping again @remicollet.  If you need this setup, we can do it easily with another mechanism.  Just let me know what you need.

I do not plan to implement this in FMN due to the issues that @pypingou pointed out above.

**Comment by remicollet** [comment]
@ralphbean sorry for the delay... long week mostly offline

Do you have any pointer to a bot (supybot ?) plugin able to read the bus and relay the message to a channel ?

**Comment by ralphbean** [comment]
@remicollet, yeah.  One is included with the core fedmsg bits, packaged in fedora as `fedmsg-irc`.

We have one running in Fedora Infrastructure at present.  Here is the config for it:  https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/fedmsg/irc/templates/ircbot.py#n28

**Comment by ralphbean** [comment]
To clarify, it is not a supybot plugin.. it is a standalone bot.

**Comment by remicollet** [comment]
This is definitively a good solution, thanks.
