### ISSUE TITLE
“Request failed with status code 422” when trying to add a destination

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/fmn#677]
When trying to add a destination, the opened up dialog shows `Error: AxiosError: Request failed with status code 422` and saving the rule also doesn’t work. When tracking the requests made by the page, a POST to `/api/v1/rule-preview` fails with:

```
  "detail": [
    {
      "loc": [
        "body",
        "tracking_rule",
        "NoParamTrackingRule",
        "params"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}
```

**Comment by nirik** [comment]
I just got this on the staging fmn test... not sure if it's not landed or it's back?
"Error: AxiosError: Request failed with status code 422" in the 'add destination' dialog...
