### ISSUE TITLE
anitya link is broken

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/fmn#69]
In the "When new upstream releases are detected" rule, the `anitya` link points to `https://apps.fedoraproject.org/notifications/<FAS-ID>.id.fedoraproject.org/email/<FILTER-ID>/release-monitoring.org/`

**Comment by ralphbean** [comment]
Thanks for reporting this.  :)

**Comment by pypingou** [comment]
fixed in https://github.com/fedora-infra/fmn.rules/pull/45
