### ISSUE TITLE
Consolidate backend service wrappers: async & sync

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/fmn#690]
# Story

As an FMN developer,
I want to be able to implement backend wrappers only once,
because I **Don’t Want to Repeat Myself™**.

# Acceptance Criteria

- [x] A mechanism exists which lets me call arbitrary async functions/methods from synchronous code
- [x] Backend wrappers employ this mechanism to make their functionality available for “both sides of the \[sync/async\] fence”.
  - [x] fasjson
  - [x] distgit/Pagure
  - [x] datagrepper
- [x] These wrappers are used across the codebase

**Comment by abompard** [comment]
Before we decide on that solution, we should also consider the other way around: calling the existing sync code from FastAPI, which is async. There are already ways to call sync code from async, and FastAPI ships with a threadpool.
I think the downside is that it introduces some overhead in the API, and thus a lack of performance. That said, the API is less performance-critical than the consumer.
Do you see another downside, Nils?

**Comment by nphilipp** [comment]
> Before we decide on that solution, we should also consider the other way around: calling the existing sync code from FastAPI, which is async. There are already ways to call sync code from async, and FastAPI ships with a threadpool. I think the downside is that it introduces some overhead in the API, and thus a lack of performance. That said, the API is less performance-critical than the consumer. Do you see another downside, Nils?

I don’t think performance issues are a problem here (yet at least), more that running async from sync looks more straight-forward to me than the opposite. The other way round, there can be unintuitive side effects like what we ran into with sending bus messages as a background task which blocked full processing of everything that is expected to be done in a handler (see #678, #679). I've already converted the one place we use `fasjson_client` to using the proxy class and at least in the automatic test it’s looking fine.

**Comment by abompard** [comment]
OK, that makes sense. I'll start working on converting the sync classes in `fmn.rules` to use the async proxies. I'll probably end up moving the classes to a shared location, so that the consumer don't depend on the API.

**Comment by nphilipp** [comment]
> OK, that makes sense. I'll start working on converting the sync classes in `fmn.rules` to use the async proxies. I'll probably end up moving the classes to a shared location, so that the consumer don't depend on the API.

Hmm, that's what I did in part on Thursday which is why I took the issue on my name, and it’s almost finished. 😉
