### ISSUE TITLE
Rule setting buttons (Include/Ignore) are backwards

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/fmn#70]
On the main page, buttons _cause_ things to happen, i.e., "Disable" turns off notifications. If you go the email/irc settings, then the "Disable this filter" turns off that filter.

But if you go edit the settings of a filter, the buttons on the individual rules show the _current status_. The only reason why I figured out it worked the other way is that the filter listing shows _just_ a status, without the button, and from there it was clear that the rules were ignored, when I really thought I was enabling them.

**Comment by ralphbean** [comment]
I agree this is confusing, but am not sure what to do about it.  To try and help clarify, here's a screenshot:

![fmn-actions](https://cloud.githubusercontent.com/assets/331338/6783312/7a55f65a-d14f-11e4-8f70-2094b6fd67ee.png)

**Comment by ralphbean** [comment]
The changes in fedora-infra/fmn.web#55 look like this:

![fmn-actions-2](https://cloud.githubusercontent.com/assets/331338/6784840/74ab74d8-d158-11e4-8e53-576d03049afc.png)

There are also tooltips now over the checkmark and the negate button that tell more about what effect they have.

**Comment by ralphbean** [comment]
@QuLogic, how does that look to you?

**Comment by pypingou** [comment]
Out of curiosity, what is the negate form for a filter represented with?

**Comment by ralphbean** [comment]
It looks like this:

![fmn-actions-3](https://cloud.githubusercontent.com/assets/331338/6786063/40ca7c06-d160-11e4-90ad-e361b4453d3e.png)

**Comment by pypingou** [comment]
Cool, my only concern is that this no longer really look like a button. Maybe a `Toggle` button on the right side of the title would help?

**Comment by ralphbean** [comment]
> this no longer really look like a button

As discussed on IRC, the little icon to the left of the filter isn't actually a button anymore.  It is just a status-indicator now.  The button got moved down to the bottom-right of the filter, next to 'delete'.

**Comment by QuLogic** [comment]
Definitely looks better and consistent that buttons _do_ stuff.
