### ISSUE TITLE
Fedora Messaging Schemas

### ISSUE THREAD

**Issue by james02135** [fedora-infra/fmn#718]
- [x] Find the list of Applications that CPE fully supports
- [x] Investigate what applications on that list need schemas written still
- [ ] Complete [Spreadsheet](https://docs.google.com/spreadsheets/d/1bppLph2WGMOn0rpi_6-E7jbKTBcHbMH8BwDWSGAT5DI/edit#gid=0)

**Comment by amoloney1** [comment]
PR opened for all critical apps within CPE remit and schemas are available for maintainers to implement as and when they choose. All other apps within CPE team are non-crit-path apps and a schema can be requested to be added when needed through the required apps tracker.
