### ISSUE TITLE
Implement emailing meeting minutes via Zodbot

### ISSUE THREAD

**Issue by decause** [fedora-infra/fmn#72]
When someone <code>#endmeeting</code>'s, this message comes up at the end of the output:

<code>< zodbot> Please remember to CC: meetingminutes@lists.fedoraproject.org on your summary/minutes email.</code>

Since we already have the meeting notes, it would be nice to perhaps craft an email like so:
**Subject** = <code>Title of the Meeting</code> - <code>Date of the Meeting</code> - <code>Chair</code>
**body** = 
- Minutes (text for sure, html also?)
- Action Items
- Link to Log

I'm tagging myself here, since I can't assign - @decause

**Comment by ralphbean** [comment]
So, we already [have code](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/supybot.py#L45-L50) in fedmsg.meta to handle getting the meeting minutes, action items, and a link to the full logs.  You just call `fedmsg.meta.msg2long_form(msg, **config)` on the message itself.  Furthermore, FMN already makes that call when it tries to format an email, so....

All we have to do is create a FAS account, get it signed up for the meetingminutes list, and create an FMN account for it with a simple rule to forward all 'meeting is done' messages there.

**Comment by ralphbean** [comment]
Its alive!  https://lists.fedoraproject.org/pipermail/meetingminutes/2015-March/001734.html
