### ISSUE TITLE
The notification was not delivered

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/fmn#766]
I created a new rule like this
![Screenshot from 2023-03-01 11-19-42](https://user-images.githubusercontent.com/6943409/222111370-a4a57777-d772-4e17-ab51-2fe88e67f01f.png)

Then I emitted this message https://apps.fedoraproject.org/datagrepper/v2/id?id=eca54a3d-7d4f-4cdc-bf70-5809c1280b64&is_raw=true and didn't get anything.

Not sure if the wildcard is issue here or the matrix destination. It could also be that I just didn't create the rule correctly.

**Comment by abompard** [comment]
That's because the anitya schema does not fill the `usernames` property (yet), as a result FMN couldn't tell that this event was referring to you and did not generate a notification.

Thanks for trying though! :-)

**Comment by Zlopez** [comment]
OK, I thought that the `agent_name` is enough.

With this information when I'm looking at https://github.com/fedora-infra/anitya-messages/pull/53, it seems that Anitya will not fit any of the tracking rules, so I'm not sure if it could be even listed as possible app. It doesn't know artifacts or users.

**Comment by abompard** [comment]
> OK, I thought that the `agent_name` is enough.

An event can *be created by* someone and  *refer to* someone(s) else, that's why we made the distinction. For events where it's the same person, it's OK to have `usernames = [agent_name]`, it's actually frequently the case.

> With this information when I'm looking at [fedora-infra/anitya-messages#53](https://github.com/fedora-infra/anitya-messages/pull/53), it seems that Anitya will not fit any of the tracking rules, so I'm not sure if it could be even listed as possible app. It doesn't know artifacts or users.

It does seem to know about users, no? Does it know about Fedora RPMs or is it just The New Hotness?

**Comment by Zlopez** [comment]
> > OK, I thought that the `agent_name` is enough.
> 
> An event can _be created by_ someone and _refer to_ someone(s) else, that's why we made the distinction. For events where it's the same person, it's OK to have `usernames = [agent_name]`, it's actually frequently the case.

But if there is only `agent_name` and the `username` is not filled, will it be ignored by FMN?

> 
> > With this information when I'm looking at [fedora-infra/anitya-messages#53](https://github.com/fedora-infra/anitya-messages/pull/53), it seems that Anitya will not fit any of the tracking rules, so I'm not sure if it could be even listed as possible app. It doesn't know artifacts or users.
> 
> It does seem to know about users, no? Does it know about Fedora RPMs or is it just The New Hotness?

The users don't need to be tied to FAS and although it has distro mappings, it doesn't validate that it's correct. In the case of the-new-hotness this is checked.

**Comment by abompard** [comment]
> But if there is only `agent_name` and the `username` is not filled, will it be ignored by FMN?

It depends on the chosen tracking rule. It will not be considered as "referring" to anyone. But you would get it if you use the "Follow a user" tracking rule, this one is based on the agent.

**Comment by Zlopez** [comment]
I tried that and adding myself as follow is working. Thanks for explanation.
