### ISSUE TITLE
Can commit email notification subject be shortened?

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/fmn#77]
Currently if someone commits to any package then email notification subject is coming with format
<committer> pushed to <pkgname> (branch). <commit message>
The 'dot' character in above message is also annoying to me.

Maybe we can have subject as
[pnemade] [nodejs-got/f22] <commit message>
We know these are commit messages so I think no need to have words "pushed to".

For commits that uploads tarballs, 
[pnemade] [nodejs-got] uploaded file got-2.4.0.tar.gz

**Comment by ralphbean** [comment]
IMO, we should go about this by adding a new `msg2subject()` api call to `fedmsg.meta` that returns a shorter subject suitable for email subject lines.

If `msg2subject()` isn't implement for a particular message type, it should fall back to a call to `msg2subtitle()` which is what we currently use.  We can implement `subject` bits then as we please.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
