### ISSUE TITLE
FMN failure "invalid type for hostInfo: <type 'NoneType'>"

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#78]
```
Date: Thu, 26 Mar 2015 13:55:04 +0000 (UTC)
From: notifications@fedoraproject.org
To: robert@fedoraproject.org
Subject: mcepl's bitlbee-3.4-1.fc23 completed
Message-Id: <20150326135504.6910C60779B6@bastion01.phx2.fedoraproject.org>
From notifications@fedoraproject.org  Thu Mar 26 14:55:12 2015

Package:    bitlbee-3.4-1.fc23
Status:     complete
Built by:   mcepl
ID:         623745
Started:    Thu, 26 Mar 2015 13:51:02 UTC
Finished:   Thu, 26 Mar 2015 13:55:00 UTC

invalid type for hostInfo: <type 'NoneType'>

        http://koji.fedoraproject.org/koji/buildinfo?buildID=623745
```

**Comment by ralphbean** [comment]
For whoever ends up taking this on, the code change is going to need to take place in the fedmsg_meta module somewhere in these lines highlighted here:  https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/buildsys.py#L60-L158

The koji client api is raising the exception (from wherever we try to use that hostInfo) and we need to handle it somewhere so we can present partial information, even if its not all there.
