### ISSUE TITLE
The placement of the New Rule button can be misleading

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fmn#789]
Also please rename the "Add a new rule" button to "Add new rule" and relocate it under the "My Rules" header.
This is to avoid the probable confusion that might happen when these two are put side-by-side.

![image](https://user-images.githubusercontent.com/95780/223460807-517ebefe-985e-4c80-a8be-55d58f32ff55.png)

For a newbie (who is using the service for the first time), it might look like clicking on that button would lead to the user creating a rule for "Specific Artifacts".
It would, of course, grow on them when they see the list changing as they change the contents of the drop down box.
But initially when the list is empty, I am 100% sure people would get confused as to what exactly the button is intended to do.

**Comment by ryanlerch** [comment]
also, not 100% sure the filter by tracking rule thing is actually useful -- how many rules do we expect people to have?
