### ISSUE TITLE
RFE: Don't send fedora-tagger notifications by default

### ISSUE THREAD

**Issue by kalev** [fedora-infra/fmn#79]
Sometimes people go on a tagging spree and I get like hundreds of emails over a night when they tag all of gnome apps or something.

 "An anonymous user gave totem a rating of 100"

I'd say this isn't interesting for the regular package maintainer and should be opt-in instead.

Thanks,
Kalev

**Comment by ralphbean** [comment]
This was requested long ago and I resisted it, but enough people have asked for it in irc that it seems now to be the right thing to do.  :+1:

This should be a simple edit to [this code in fmn.lib](https://github.com/fedora-infra/fmn.lib/blob/develop/fmn/lib/defaults.py#L16-L21) if anyone wants to take it on.
