### ISSUE TITLE
can't follow messages from user "bodhi"

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/fmn#793]
I tried to follow users from the user "bodhi", but it doenst seem to show up in the search.

The user "autopen" works, however.

the bodhi user hasn't signed the FPCA though -- are we only searching for users that have signed the agreement?

**Comment by abompard** [comment]
Yeah, the bodhi user is not even a Fedora account, it's in IPA but not with the `fasuser` objectclass.
