### ISSUE TITLE
Incorrect links for Bodhi updates

### ISSUE THREAD

**Issue by kalev** [fedora-infra/fmn#81]
Bodhi update links don't include the update ID. This means that every time an update is edited, it invalidates the link in the FMN email.

The links should include the update ID, such as https://admin.fedoraproject.org/updates/FEDORA-2015-4700/

For example, instead of:

elad commented on bodhi update adwaita-icon-theme-3.16.0-1.fc22,ai... (karma: 1)
    https://admin.fedoraproject.org/updates/adwaita-icon-theme-3.16.0-1.fc22,aisleriot-3.16.0-1.fc22,anjuta-3.16.0-1.fc22,atk-2.16.0-1.fc22,atomix-3.16.0-1.fc22,at-spi2-atk-2.16.0-1.fc22,at-spi2-core-2.16.0-1.fc22,baobab-3.16.0-1.fc22,bijiben-3.16.0-1.fc22,california-0.4.0-1.fc22,caribou-0.4.18-1.fc22,cheese-3.16.0-1.fc22,clutter-1.22.0-1.fc22,cogl-1.20.0-3.fc22,control-center-3.16.0-1.fc22,dconf-0.24.0-1.fc22,dconf-editor-3.16.0-1.fc22,devhelp-3.16.0-1.fc22,eog-3.16.0-1.fc22,eog-plugins-3.16.0-1.fc22,epiphany-3.16.0-1.fc22,evince-3.16.0-1.fc22,evolution-3.16.0-1.fc22,evolution-data-server-3.16.0-1.fc22,evolution-ews-3.16.0-1.fc22,evolution-mapi-3.16.0-1.fc22,file-roller-3.16.0-1.fc22,five-or-more-3.16.0-1.fc22,four-in-a-row-3.16.0-1.fc22,gdm-3.16.0.1-1.fc22,gedit-3.16.0-1.fc22,gedit-code-assistance-3.14.3-1.fc22,gedit-plugins-3.16.0-1.fc22,geocode-glib-3.16.0-1.fc22,gitg-3.16.0-1.fc22,glib2-2.44.0-1.fc22,glibmm24-2.44.0-1.fc22,glib-networking-2.44.0-1.fc22,gnome-backgrounds-3.16.0-1.fc
 22,gnome-bluetooth-3.16.0-1.fc22,gnome-boxes-3.16.0-1.fc22,gnome-builder-3.16.0-1.fc22,gnome-calculator-3.16.0-1.fc22,gnome-calendar-3.16.0-1.fc22,gnome-characters-3.16.0-1.fc22,gnome-chess-3.16.0-1.fc22,gnome-clocks-3.16.0-1.fc22,gnome-color-manager-3.16.0-1.fc22,gnome-contacts-3.16.0-1.fc22,gnome-desktop3-3.16.0-1.fc22,gnome-devel-docs-3.16.0-1.fc22,gnome-dictionary-3.16.0-1.fc22,gnome-disk-utility-3.16.0-1.fc22,gnome-documents-3.16.0-1.fc22,gnome-font-viewer-3.16.0-1.fc22,gnome-getting-started-docs-3.16.0-1.fc22,gnome-initial-setup-3.16.0-1.fc22,gnome-klotski-3.16.0-1.fc22,gnome-logs-3.16.0-1.fc22,gnome-mahjongg-3.16.0-1.fc22,gnome-maps-3.16.0-1.fc22,gnome-mines-3.16.0-1.fc22,gnome-multi-writer-3.16.0-1.fc22,gnome-music-3.16.0-1.fc22,gnome-nibbles-3.16.0-1.fc22,gnome-online-accounts-3.16.0-1.fc22,gnome-packagekit-3.16.0-1.fc22,gnome-photos-3.16.0-1.fc22,gnome-power-manager-3.16.0-1.fc22,gnome-robots-3.16.0-1.fc22,gnome-screenshot-3.16.0-1.fc22,gnome-session-3.16.0-1.fc22,gnome-se
 ttings-daemon-3.16.0-1.fc22,gnome-shell-3.16.0-1.fc22,gnome-shell-extension-background-logo-3.16.0-1.fc22,gnome-shell-extensions-3.16.0-1.fc22,gnome-software-3.16.0-1.fc22,gnome-sound-recorder-3.16.0-1.fc22,gnome-sudoku-3.16.0-1.fc22,gnome-system-monitor-3.16.0-1.fc22,gnome-taquin-3.16.0-1.fc22,gnome-terminal-3.16.0-1.fc22,gnome-tetravex-3.16.0-1.fc22,gnome-themes-standard-3.16.0-1.fc22,gnome-tweak-tool-3.16.0-1.fc22,gnome-user-docs-3.16.0-1.fc22,gnome-weather-3.16.0-1.fc22,gobject-introspection-1.44.0-1.fc22,gsettings-desktop-schemas-3.16.0-1.fc22,gtk3-3.16.0-1.fc22,gtkmm30-3.16.0-1.fc22,gtksourceview3-3.16.0-1.fc22,gucharmap-3.16.0-1.fc22,gvfs-1.24.0-1.fc22,hicolor-icon-theme-0.15-1.fc22,iagno-3.16.0-1.fc22,libgdl-3.16.0-1.fc22,libgee-0.18.0-1.fc22,libgexiv2-0.10.3-1.fc22,libgit2-glib-0.22.2-1.fc22,libgweather-3.16.0-1.fc22,libpeas-1.14.0-1.fc22,libsoup-2.50.0-1.fc22,lightsoff-3.16.0-1.fc22,mutter-3.16.0-1.fc22,nautilus-3.16.0-1.fc22,orca-3.16.0-1.fc22,pangomm-2.36.0-1.fc22,polari
 -3.16.0-1.fc22,pyatspi-2.16.0-1.fc22,pygobject3-3.16.0-1.fc22,quadrapassel-3.16.0-1.fc22,rygel-0.26.0-1.fc22,shotwell-0.22.0-1.fc22,simple-scan-3.16.0.1-1.fc22,sound-juicer-3.16.0-1.fc22,swell-foop-3.16.0-1.fc22,tali-3.16.0-1.fc22,totem-3.16.0-1.fc22,tracker-1.4.0-1.fc22,vala-0.28.0-1.fc22,vinagre-3.16.0-1.fc22,vino-3.16.0-1.fc22,vte291-0.40.0-1.fc22,webkitgtk4-2.8.0-1.fc22,yelp-3.16.0-1.fc22,yelp-xsl-3.16.0-1.fc22

it should be:

https://admin.fedoraproject.org/updates/FEDORA-2015-4700/adwaita-icon-theme-3.16.0-1.fc22,aisleriot-3.16.0-1.fc22,anjuta-3.16.0-1.fc22,atk-2.16.0-1.fc22,atomix-3.16.0-1.fc22,at-spi2-atk-2.16.0-1.fc22,at-spi2-core-2.16.0-1.fc22,baobab-3.16.0-1.fc22,bijiben-3.16.0-1.fc22,california-0.4.0-1.fc22,caribou-0.4.18-1.fc22,cheese-3.16.0-1.fc22,clutter-1.22.0-1.fc22,cogl-1.20.0-3.fc22,control-center-3.16.0-1.fc22,dconf-0.24.0-1.fc22,dconf-editor-3.16.0-1.fc22,devhelp-3.16.0-1.fc22,eog-3.16.0-1.fc22,eog-plugins-3.16.0-1.fc22,epiphany-3.16.0-1.fc22,evince-3.16.0-1.fc22,evolution-3.16.0-1.fc22,evolution-data-server-3.16.0-1.fc22,evolution-ews-3.16.0-1.fc22,evolution-mapi-3.16.0-1.fc22,file-roller-3.16.0-1.fc22,five-or-more-3.16.0-1.fc22,four-in-a-row-3.16.0-1.fc22,gdm-3.16.0.1-1.fc22,gedit-3.16.0-1.fc22,gedit-code-assistance-3.14.3-1.fc22,gedit-plugins-3.16.0-1.fc22,geocode-glib-3.16.0-1.fc22,gitg-3.16.0-1.fc22,glib2-2.44.0-1.fc22,glibmm24-2.44.0-1.fc22,glib-networking-2.44.0-1.fc22,gnome-backgrounds-3.16.0-1.fc22,gnome-bluetooth-3.16.0-1.fc22,gnome-boxes-3.16.0-1.fc22,gnome-builder-3.16.0-1.fc22,gnome-calculator-3.16.0-1.fc22,gnome-calendar-3.16.0-1.fc22,gnome-characters-3.16.0-1.fc22,gnome-chess-3.16.0-1.fc22,gnome-clocks-3.16.0-1.fc22,gnome-color-manager-3.16.0-1.fc22,gnome-contacts-3.16.0-1.fc22,gnome-desktop3-3.16.0-1.fc22,gnome-devel-docs-3.16.0-1.fc22,gnome-dictionary-3.16.0-1.fc22,gnome-disk-utility-3.16.0-1.fc22,gnome-documents-3.16.0-1.fc22,gnome-font-viewer-3.16.0-1.fc22,gnome-getting-started-docs-3.16.0-1.fc22,gnome-initial-setup-3.16.0-1.fc22,gnome-klotski-3.16.0-1.fc22,gnome-logs-3.16.0-1.fc22,gnome-mahjongg-3.16.0-1.fc22,gnome-maps-3.16.0-1.fc22,gnome-mines-3.16.0-1.fc22,gnome-multi-writer-3.16.0-1.fc22,gnome-music-3.16.0-1.fc22,gnome-nibbles-3.16.0-1.fc22,gnome-online-accounts-3.16.0-1.fc22,gnome-packagekit-3.16.0-1.fc22,gnome-photos-3.16.0-1.fc22,gnome-power-manager-3.16.0-1.fc22,gnome-robots-3.16.0-1.fc22,gnome-screenshot-3.16.0-1.fc22,gnome-session-3.16.0-1.fc22,gnome-settings-daemon-3.16.0-1.fc22,gnome-shell-3.16.0-1.fc22,gnome-shell-extension-background-logo-3.16.0-1.fc22,gnome-shell-extensions-3.16.0-1.fc22,gnome-software-3.16.0-1.fc22,gnome-sound-recorder-3.16.0-1.fc22,gnome-sudoku-3.16.0-1.fc22,gnome-system-monitor-3.16.0-1.fc22,gnome-taquin-3.16.0-1.fc22,gnome-terminal-3.16.0-1.fc22,gnome-tetravex-3.16.0-1.fc22,gnome-themes-standard-3.16.0-1.fc22,gnome-tweak-tool-3.16.0-1.fc22,gnome-user-docs-3.16.0-1.fc22,gnome-weather-3.16.0-1.fc22,gobject-introspection-1.44.0-1.fc22,gsettings-desktop-schemas-3.16.0-1.fc22,gtk3-3.16.0-1.fc22,gtkmm30-3.16.0-1.fc22,gtksourceview3-3.16.0-1.fc22,gucharmap-3.16.0-1.fc22,gvfs-1.24.0-1.fc22,hicolor-icon-theme-0.15-1.fc22,iagno-3.16.0-1.fc22,libgdl-3.16.0-1.fc22,libgee-0.18.0-1.fc22,libgexiv2-0.10.3-1.fc22,libgit2-glib-0.22.2-1.fc22,libgweather-3.16.0-1.fc22,libpeas-1.14.0-1.fc22,libsoup-2.50.0-1.fc22,lightsoff-3.16.0-1.fc22,mutter-3.16.0-1.fc22,nautilus-3.16.0-1.fc22,orca-3.16.0-1.fc22,pangomm-2.36.0-1.fc22,polari-3.16.0-1.fc22,pyatspi-2.16.0-1.fc22,pygobject3-3.16.0-1.fc22,quadrapassel-3.16.0-1.fc22,rygel-0.26.0-1.fc22,shotwell-0.22.0-1.fc22,simple-scan-3.16.0.1-1.fc22,sound-juicer-3.16.0-1.fc22,swell-foop-3.16.0-1.fc22,tali-3.16.0-1.fc22,totem-3.16.0-1.fc22,tracker-1.4.0-1.fc22,vala-0.28.0-1.fc22,vinagre-3.16.0-1.fc22,vino-3.16.0-1.fc22,vte291-0.40.0-1.fc22,webkitgtk4-2.8.0-1.fc22,yelp-3.16.0-1.fc22,yelp-xsl-3.16.0-1.fc22

**Comment by kalev** [comment]
Also, there's a line break in the first link -- I didn't typo it, it's how FMN sent the link. Obviously it doesn't work if there's a line break in the middle.

**Comment by ralphbean** [comment]
Thanks for this!

The relevant code that needs changing is in the fedmsg_meta_fedora_infrastructure module, in the BodhiProcessor in the `link` method [here](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/bodhi.py#L244-L276)

Note that, I think that update id is called the update `alias` in the msg payload.  And it is not guaranteed to always be present.  In that `link` method, we should check if its present and use it if it is.  Otherwise, fall back to `update_title`.

**Comment by ralphbean** [comment]
> Note that, I think that update id is called the update alias in the msg payload. And it is not guaranteed to always be present.

I was mistaken here.  It looks like the msg alias is _never_ passed along to fedmsg so we have no way to construct this nice link on the receiving side for now.  Let's make sure bodhi2 passes that value along.  Filed that as fedora-infra/bodhi#133.

**Comment by lmacken** [comment]
I think the bodhi conglomerator will need updating as well? https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/conglomerators/bodhi/requests.py#L103-L104
