### ISSUE TITLE
500 error on "about" page when logged in

### ISSUE THREAD

**Issue by ktdreyer** [fedora-infra/fmn#82]
Steps to reproduce:
1. Log in
2. Click the "about" link in the header (https://apps.fedoraproject.org/notifications/about)

Results:
"500 Internal server error"

Expected results:
Web page displays normally

Additional info:
I can only reproduce this crash when logged in. When I clear my browser's cookies, https://apps.fedoraproject.org/notifications/about works fine.

**Comment by ralphbean** [comment]
Yeah, this is a regression that got introduced earlier in the week.  Sorry!
