### ISSUE TITLE
FMN failure "internal error in 'INIT': %d format: a number is required, not str"

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#83]
```
Date: Mon, 30 Mar 2015 09:58:45 +0000 (UTC)
From: notifications@fedoraproject.org
To: robert@fedoraproject.org
Subject: pbrobinson's phpMyAdmin-4.3.13-1.fc23 completed (arm)
Message-Id: <20150330095845.D03F860600C5@bastion01.phx2.fedoraproject.org>
From notifications@fedoraproject.org  Mon Mar 30 11:58:51 2015

Package:    phpMyAdmin-4.3.13-1.fc23
Status:     complete
Built by:   pbrobinson
ID:         270460
Started:    Mon, 30 Mar 2015 09:59:01 UTC
Finished:   Mon, 30 Mar 2015 09:59:01 UTC

<Fault 1: "<class 'pg.OperationalError'>: internal error in 'INIT': %d format: a number is required, not str">

        http://arm.koji.fedoraproject.org/koji/buildinfo?buildID=270460
```

**Comment by pypingou** [comment]
Looking at the code, the only place where I saw a `%d` is in the date formatting, and this seems to work fine :disappointed:

**Comment by robert-scheck** [comment]
Note that this is ARM (if that makes any difference). Is this issue maybe related to #78?

**Comment by ralphbean** [comment]
The error is actually coming from the arm koji instance's xmlrpc interface.  (so the 'pg' bit is the postgres database on the koji server side).  I don't know any more than that off the bat.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
