### ISSUE TITLE
Nondescriptive message: spot updated action 2 from Pending to Awaiting Review

### ISSUE THREAD

**Issue by ppisar** [fedora-infra/fmn#85]
I received this e-mail notification:

```
Date: Mon, 30 Mar 2015 18:23:49 +0000 (UTC)
From: notifications@fedoraproject.org
To: perl-devel@lists.fedoraproject.org
Subject: spot updated action 2 from Pending to Awaiting Review

spot updated action 2 from Pending to Awaiting Review
```

Except for the person name, I have no idea what it is about. Please make this kind of notifications more useful.

**Comment by pypingou** [comment]
So this is coming from a message sent by pkgdb, when spot accepted the epel7 branch for `perl-Email-Reply`.

We have a more informative message via `pkgdb-admin list all`

```
....
#2 (Approved) - pghmcfc requested a new branch "epel7" for "perl-Email-Reply"
```

That being said, I do not know if FMN has access to these information.

**Comment by pypingou** [comment]
Messages relating to this:
- spot's message: https://apps.fedoraproject.org/datagrepper/id?id=2015-492a47e4-7887-4914-b9b6-e9f190c9bac9&is_raw=true&size=extra-large
- Kevin granting the request: https://apps.fedoraproject.org/datagrepper/id?id=2015-08f8214d-ba96-46bb-b0bd-a3743cc7d00e&is_raw=true&size=extra-large

**Comment by pypingou** [comment]
Maybe we could re-use the code from pkgdb-admin: https://github.com/fedora-infra/packagedb-cli/blob/master/pkgdb2client/admin.py#L116 ?

**Comment by ralphbean** [comment]
@pypingou, can we modify pkgdb to put more useful data in the fedmsg message in the first place?

A more descriptive string would help.  The ability to construct a link to view something in pkgdb would be very nice to have also.

**Comment by pypingou** [comment]
It seems we have all the info we need in the message, we have the action type, the package name, the branch the change of status that should be fine.

As for the link, in pkgdb UI you can only see your actions (or all for the admins via the admin panel), so the link will most of the time not be that useful.
