### ISSUE TITLE
Untangle the branches

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/fmn#853]
# Story

As an engineer working on FMN,
I want that the branches in the git repository have meaningful and up to date names,
so that I know what exactly I’m working on.

# Acceptance Criteria

- [ ] The new FMN code and its history is available in the `develop` branch. Anything automated that refers to this branch is updated accordingly (S2I?), and/or a branch alias is introduced (similar to `main` ⇒ `rawhide` in distgit).
- [ ] The old FMN code and its history is available in the `develop-old` branch.
- [ ] Maintainers of the old code are informed upfront of the change so that they are not taken by surprise. 

# Background

- **Current state** is: Old FMN uses `develop`, new FMN uses `fmn-next`.
- **Desired state** is: Old FMN uses e.g. `develop-old`, new FMN uses `develop` (and `stg` and `prod` or `testing` and `stable`, but that’s for later).

If we simply shuffle branches around without telling anybody, people might get weird surprises when pulling.

**Comment by abompard** [comment]
Done! :-)
