### ISSUE TITLE
[RFE] Cancel button on editing rules

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/fmn#877]
When editing rules, I'd like to have a Cancel button if I don't want to save changes.

**Comment by abompard** [comment]
Good point! At the moment you can click on the logo to go back to your list of rules, but a cancel button would be nice I think.

**Comment by ferdnyc** [comment]
Separate from / in addition to this request, having the "Notifications" logo be the _only_ path to viewing **your own** set of rules is a bit unintuitive. Perhaps a "Profile" or "Rules" entry under the user menu, to keep "Logout" company, would better match users' navigation expectations.
