### ISSUE TITLE
The-new-hotness sends direct emails when monitoring is turned off

### ISSUE THREAD

**Issue by kalev** [fedora-infra/fmn#88]
When a package has update monitoring turned _off_, the-new-hotness still sends direct emails about package updates:

```
To: kalevlember@gmail.com
From: notifications@fedoraproject.org
Subject: the-new-hotness saw an update for gnome-builder, but pkgdb says the package owner is not interested in bugs being filed

the-new-hotness saw an update for gnome-builder, but pkgdb says the package owner is not interested in bugs being filed
    https://release-monitoring.org/project/5574/
```

Some issues here:
 1) If I have monitoring turned off, then I probably don't want to be notified about the available update
 2) The notification has very little data -- what does it mean "saw an update" ? Does it mean that it saw that I updated the package? Does it mean it noticed that there's an upstream release available? What versions?

In addition to that email, it was immediately followed by another one, with a little bit more data:

```
To: kalevlember@gmail.com
From: notifications@fedoraproject.org
Subject: A new version of "gnome-builder" has been detected: "3.16.2" in advance of "3.16.1", packaged as "gnome-builder"

A new version of "gnome-builder" has been detected:  "3.16.2" in advance of "3.16.1", packaged as "gnome-builder"
    https://release-monitoring.org/project/5574/
```

Issues here:
 1) Again, update monitoring is turned off for that package.
 2) The notification is incorrect because the package was already updated at that point. gnome-builder 3.16.2 builds had already finished 14 hours earlier for both rawhide and F22.

**Comment by tomhughes** [comment]
This just came up again on #fedora-devel...

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
