### ISSUE TITLE
koji build notifications say that the task is not finished

### ISSUE THREAD

**Issue by kalev** [fedora-infra/fmn#89]
All build completed notifications from koji say that the task is not finished, which looks a lot like an error message. Would be good if it could wait with the email until the task is actually finished, so that it doesn't have to include the complaint about unfinished tasks.

```
To: kalevlember@gmail.com
From: notifications@fedoraproject.org
Subject: kalev's rhythmbox-3.2.1-1.fc22 completed

Package:    rhythmbox-3.2.1-1.fc22
Status:     complete
Built by:   kalev
ID:         629305
Started:    Sun, 19 Apr 2015 11:14:20 UTC
Finished:   Sun, 19 Apr 2015 11:30:40 UTC

Closed tasks:
-------------
Task 9512844 on arm02-builder21.arm.fedoraproject.org
Task Type: build (noarch)
Link: https://koji.fedoraproject.org/koji/taskinfo?taskID=9512844

Task 9512844 is not finished
```

**Comment by ralphbean** [comment]
Thinking about this:  we could go about it in two different ways:
- Koji is to blame here.  The koji hub calls the "build is done" plugins _before_ the build is actually done.  fedmsg is fast enough that our plugin sends a message across our infrastructure to the notifications backend which in turn queries koji to get the details of the build... but the koji api throws an error, telling us that the build is not done.  We should fix koji to move that plugin call until after the build is actually done.  (however, the koji code base is scary and upstream is slow to respond to patches).
- We could put a shim in our querying code that simply waits if the task is not done.  It should finish sometime, right?  This could introduce message pile-up on our end and so is less attractive.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
