### ISSUE TITLE
add rules for new meeting topics

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fmn#90]
We added messages for info/action/agreed recently to meetings, but there's no way to match on those in FMN. 

In particular I want a way to get start/end for meetings where I speak up, but none of the info/action/agreed stuff. I often find myself saying one or two things in a meeting to clarify something but otherwise am not interested in the rest of the meeting. 

Perhaps a way to say "all meetings where ircnick is chair" but nothing else. 
Or just a way to say "I don't want to know about everything in all meetings where I say one thing"

**Comment by ralphbean** [comment]
For anyone interested in taking this on, it should be an easy fix to add them to the [fmn.rules repository](https://github.com/fedora-infra/fmn.rules).
