### ISSUE TITLE
Wrong link to src.fp.o

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/fmn#905]
I've just received a notification about a commit pushed by a collaborator in one package repository I maintain:
```
New commit: 1 commits
By: marcdeop
https://pagure.io/rpms/kpmcore/tree/rawhide
```
The link repports `pagure.io`, but it should be `src.fedoraproject.org`. I don't know where the base domain come from, though: the message which have triggered the notification reports it right, I think it is https://apps.fedoraproject.org/datagrepper/v2/id?id=d15672d9-b28f-4591-8ebe-50866b6404c5&is_raw=true&size=extra-large

**Comment by abompard** [comment]
Thanks for the report and the link, Mattia. Indeed it's a bug in Pagure's message schemas, I've reported it here: https://www.pagure.io/pagure-messages/issue/9
