### ISSUE TITLE
FMN does not allow adding destinations to a rule

### ISSUE THREAD

**Issue by gotmax23** [fedora-infra/fmn#912]
When I try to add a destination to a rule, I get an `Unable to get the available destinations, please try again later` error. This makes it impossible for me to use FMN.

![Screenshot of the error message](https://github.com/fedora-infra/fmn/assets/9920591/42d749a8-e938-4277-8eee-451eb2172840)

**Comment by gotmax23** [comment]
It looks like it's trying to make a request to https://fmn-api.apps.ocp.fedoraproject.org/api/v1/users/gotmax23/destinations and then getting a HTTP 500 error.

**Comment by justwheel** [comment]
I can also reproduce this.

**Comment by mjg** [comment]
Still there. It's a pitty we have that when people are trying to follow along with the release party talk on FMN.

**Comment by abompard** [comment]
I haven't been able to reproduce it yet, but I'm looking into it! Thanks for reporting and confirming.

**Comment by mjg** [comment]
```
index-80312ce4.js:21     GET https://fmn-api.apps.ocp.fedoraproject.org/api/v1/users/mjg/destinations 500 (Internal Server Error)
```
Not sure if the console log of that request helps:
[notifications.fedoraproject.org-1685791420169.log](https://github.com/fedora-infra/fmn/files/11642473/notifications.fedoraproject.org-1685791420169.log)
(Happens right after new rule/add destination, where it seems to "hang" for a moment before possibly filling in the destinations menu; request fails, error pops up right after that in the log and and in the dialog as per the screenshot).

**Comment by mjg** [comment]
Is there any progress or new insight on this?

It's nice to have presentations about the new greatness, but some of us are locked out from the beginning. Is there anything we can do to help track this down?

**Comment by abompard** [comment]
Hey! Sorry, this issue had fallen under my radar. I'll get back to it tomorrow. It's happening every time for you?

**Comment by mjg** [comment]
> Hey! Sorry, this issue had fallen under my radar. I'll get back to it tomorrow. It's happening every time for you?

Yes, always. I tried every time you gave a talk on fmn and I wanted to follow along ;-)

That is, I have no rules and cannot add any just like in @gotmax23 's screenshot. Double checked matrix and e-mail settings in fas. Logged out and in etc. I have no problems with other infra like bodhi, dist-git, dashboard and the old fmn which all can query fas for my account. All of this across multiple chrome versions by now.

One thing that may or may not matter: FAS does not (or did not) allow you to use an f.p.o. e-mail address as the primary address. That primary address of mine uses "+" parts in the username part. My mjg@f.p.o. address aliases that.

**Comment by abompard** [comment]
And you are correct! There's a regexp somewhere that did not validate the email address with the extension part. I'll fix it right now.

**Comment by abompard** [comment]
This does not seem to be the same issue that @gotmax23 is having, though. Maxwell, could you please try again so I can check out the traceback in the logs? (I can't go digging very far in the past with our openshift logs)
Thanks.

**Comment by gotmax23** [comment]
It eventually started working for me, but I forgot to update the issue.

**Comment by mjg** [comment]
Just to be sure - this change is not live in production yet, is it? (Not complaining, just cross-checking.)

**Comment by abompard** [comment]
It's not, but it is on staging. Do you mind trying out https://notifications.stg.fedoraproject.org please ?

**Comment by mjg** [comment]
> It's not, but it is on staging. Do you mind trying out https://notifications.stg.fedoraproject.org please ?

That tries to authenticate me against id.stg.fpo (not id.fpo), which results in "Authentication failure" with my usual credentials. I guess we'll have to wait for this go live then for confirmation. Thanks in any case!
