### ISSUE TITLE
Missing commit diff in "[Pagure] <fas> pushed 1 commits on rpms/<pkg> (branch: main)" mails

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#916]
I am sorry, but the new FMN mails for commits to src.fedoraproject.org lost somehow their value for me; example:

```
Date: Fri,  2 Jun 2023 19:27:17 +0000 (UTC)
From: Fedora Notifications <notifications@fedoraproject.org>
To: <me>
Subject: [Pagure] <fas> pushed 1 commits on rpms/<pkg> (branch: main)

New commit: 1 commits
By: <fas>
https://src.fedoraproject.org/rpms/<pkg>/tree/main
```

In difference, the old FMN mails contained a diff of the actual Git commit (including the commit hash)…which I kindly would prefer to receive again :)

**Comment by abompard** [comment]
The change is deployed to prod as of this morning, hopefully it'll be more useful now.

**Comment by robert-scheck** [comment]
Yes, it is – thank you.
