### ISSUE TITLE
Missing build data in "[Koji] Build COMPLETE: <fas>'s <pkg-nvr>" mails

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#917]
I am sorry, but the new FMN mails for builds at koji.fedoraproject.org lost somehow their value for me; example:

```
Date: Fri,  2 Jun 2023 19:39:10 +0000 (UTC)
From: Fedora Notifications <notifications@fedoraproject.org>
To: <me>
Subject: [Koji] Build COMPLETE: <fas>'s <pkg-nvr>

Build COMPLETE: <fas>'s <pkg-nvr>
```

In difference, the old FMN mails contained a link to the specific build, the Koji tags etc. (and a long long time ago they even contained direct links to the build artifacts aka RPMs and build logs)…which I kindly would prefer to receive again :)

**Comment by abompard** [comment]
With c455a2c53, the messages should be much better. I'll deploy it to prod soon.
