### ISSUE TITLE
Make digests be actual digests

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/fmn#92]
The "digests" sent by FMN don't appear to be actual email digests.  As such, mail readers which can unpack digests don't unpack them properly.  Please consider using either standard MIME digests, or RFC 1153-format digests.

**Comment by pypingou** [comment]
The mentioned RFC: https://tools.ietf.org/html/rfc1153

**Comment by jasontibbitts** [comment]
FYI, the MIME digests are defined in RFC 2046 section 5.1.5.

http://tools.ietf.org/html/rfc2046#section-5.1.5

RFC 1153 is https://tools.ietf.org/html/rfc1153

Both formats are very simple and the MIME one is probably already supported by whatever email generation library you're using.

**Comment by pypingou** [comment]
More on digests by mailman: http://www.gnu.org/software/mailman/mailman-admin/node19.html

**Comment by ralphbean** [comment]
I looked into this some this morning but didn't find any obvious solutions off the bat.  I'd gladly accept code to make this work but would appreciate if someone else could take it on (I'll circle back eventually after getting through some other issues/other projects if no-one gets here first).

**Comment by jasontibbitts** [comment]
I can try to take a look if I can find the time, but if you could give a hint as to where in the code I'd start looking in order to hook this in, I'd appreciate it.

**Comment by ralphbean** [comment]
Sure thing!  Maybe start with the `handle_batch` code here:  https://github.com/fedora-infra/fmn.consumer/blob/develop/fmn/consumer/backends/mail.py#L114-L145

There should be instructions to help setup a development environment in the readme here:  https://github.com/fedora-infra/fmn#hacking

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
