### ISSUE TITLE
"Unable to get the available destinations, please try again later." error when trying to add a new destination to a rule

### ISSUE THREAD

**Issue by rathann** [fedora-infra/fmn#931]
Steps to reproduce:

1. log in at https://notifications.fedoraproject.org
2. go to an existing "My packages" rule (artifacts by user rathann with destinations to e-mail and IRC)
3. click on "Add another destination"

Error message appears. "Destinations" drop-down is greyed-out and not clickable.

**Comment by abompard** [comment]
This looks like #912, does it seem to be the same to you as well?

**Comment by rathann** [comment]
Yes, looks like I made a duplicate, closing.
