### ISSUE TITLE
Emails lack character encoding information

### ISSUE THREAD

**Issue by Rombobeorn** [fedora-infra/fmn#94]
Invalid emails are being sent out. They contain what was supposed to be non-English letters, but they don't specify which character encoding was used. Such invalid messages may be rejected by a receiving MTA. If they are accepted anyway, they are likely to be displayed as mojibake on the recipient's screen.

https://en.wikipedia.org/wiki/Mojibake

Email messages must always be MIME encoded, unless it can be proven that they will only ever contain pure 7-bit ASCII text, and that is not your case.

https://tools.ietf.org/html/rfc2045

**Comment by ralphbean** [comment]
All our emails are all encoded as utf-8.

Adding these headers should be sufficient to fix the issue here, correct?

```
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
```

**Comment by Rombobeorn** [comment]
Those MIME-Version and Content-Type header fields are correct.

If you specify Base64 then you must also encode the message in Base64.

The alternative is to do no encoding, specify
"Content-Transfer-Encoding: 8bit", request 8BITMIME in the SMTP
session, and verify that the server replies that it supports 8BITMIME.
That way you offload the encoding work to the MTA. Postfix knows how to
apply a transfer encoding if it needs to forward a message to another
MTA that doesn't support 8BITMIME.

**Comment by cydrobolt** [comment]
@ralphbean You removed the Content-Transfer-Encoding header, which seems to have broken the encoding. Not sure if this was intentional, but it seems like the emails are displayed as Base64 now.

https://github.com/fedora-infra/fmn.consumer/pull/65

**Comment by jeremycline** [comment]
Since https://github.com/fedora-infra/fmn.consumer/pull/65 is merged I'm going to close this as fixed.
