### ISSUE TITLE
No Git diff for "[Pagure] <fas> pushed 2 commits on rpms/<pkg> (branch: <branch>)"

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#949]
The old FMN send **two** e-mails for this case, each with a Git diff. The new one sends one e-mail, with no Git diff at all, just with a link. Any chance to improve this behaviour? I like to archive such Git diffs, thus a link has less value for me compared to the actual diff.

```
Date: Wed, 12 Jul 2023 18:11:50 +0000 (UTC)
From: Fedora Notifications <notifications@fedoraproject.org>
To: <me>
Subject: [Pagure] <fas> pushed 2 commits on rpms/<pkg> (branch: <branch>)

John Doe (<fas>) pushed 2 commits on rpms/<pkg>.
Branch: <branch>

https://src.fedoraproject.org/rpms/openbgpd/c/8ccf7c1d460a354e2fccbc4ac433e406d453b756..2435104bec4a340f0bcda4186365d509e8d5abe0
```

**Comment by abompard** [comment]
Transferred at: https://www.pagure.io/pagure-messages/issue/11
