### ISSUE TITLE
new fmn does not support RHBZ / BugZilla events

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/fmn#991]
One of the nice features of the old notifications system was that I got real-time notifications whenever bugs that I was associated with (assignee, reporter, CC) changed state (in addition to email notifications). It would be great if this could be supported in by new notifications system as well.

**Comment by abompard** [comment]
To do that, the Bugzilla2Fedmsg schemas should be split off https://github.com/fedora-infra/bugzilla2fedmsg and into their own repository/package, so that FMN can install them.

**Comment by abompard** [comment]
Reported to the bugzilla2fedmsg repo
