### ISSUE TITLE
missing artifact / group rules for pagure.io

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/fmn#999]
I get *some* notifications from pagure.io because I set up a filter for "My Events" with "Pagure" application enabled, but getting notifications for things that I do myself but *no* notifications for things that others do is not ideal.

I also don't see a way to set up a filter for notifications for specific projects ("Artifacts") on pagure.io, and also no way to say "I want to get notifications for all repositories in this group on pagure.io (since groups are only taken from FAS, not from pagure.io, I assume).

**Comment by abompard** [comment]
> I get _some_ notifications from pagure.io because I set up a filter for "My Events" with "Pagure" application enabled, but getting notifications for things that I do myself but _no_ notifications for things that others do is not ideal.

With this rule, you should be getting notifications for things that others do but "impact" you, such as someone editing one of your packages for example.

> I also don't see a way to set up a filter for notifications for specific projects ("Artifacts") on pagure.io,

Yeah you can request notifications for things that are produced by Fedora, such as RPMs. So that's not on pagure.io but on dist-git. 

> and also no way to say "I want to get notifications for all repositories in this group on pagure.io (since groups are only taken from FAS, not from pagure.io, I assume).

Correct, groups are taken from FAS.

It sounds like you would like to be able to subscribe to projects and groups on pagure.io, but a lot of things there aren't related to Fedora (or don't have to be), so I'm not sure it falls within the remit of FMN.

**Comment by decathorpe** [comment]
> > I get _some_ notifications from pagure.io because I set up a filter for "My Events" with "Pagure" application enabled, but getting notifications for things that I do myself but _no_ notifications for things that others do is not ideal.
> 
> With this rule, you should be getting notifications for things that others do but "impact" you, such as someone editing one of your packages for example.

That does not seem to be the case. I got a notifications for my *own* comments on pull requests on https://pagure.io/fedora-rust/rust-packaging, but I get no notifications for comments that *others* post on my PRs.

> > I also don't see a way to set up a filter for notifications for specific projects ("Artifacts") on pagure.io,
> 
> Yeah you can request notifications for things that are produced by Fedora, such as RPMs. So that's not on pagure.io but on dist-git.
> 
> > and also no way to say "I want to get notifications for all repositories in this group on pagure.io (since groups are only taken from FAS, not from pagure.io, I assume).
> 
> Correct, groups are taken from FAS.
> 
> It sounds like you would like to be able to subscribe to projects and groups on pagure.io, but a lot of things there aren't related to Fedora (or don't have to be), so I'm not sure it falls within the remit of FMN.

Right ... but it's weird that I can set up to get *some* notifications from pagure.io, but not others.

**Comment by abompard** [comment]
Ah, I see. This may be something to fix on the pagure message schemas. It could be that it's not putting your name in the `usernames` property when someone else comments on your PR.

**Comment by abompard** [comment]
Yeah I think that should be implemented here: https://www.pagure.io/pagure-messages/blob/master/f/pagure_messages/pull_requests_schema.py#_154

I'll open a ticket in the repo.

**Comment by abompard** [comment]
Reported in the pagure-messages repo: https://www.pagure.io/pagure-messages/issue/12
